# -*- coding: utf-8 -*-
"""cse151b_final_notebook.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bliWWyc6ubUhngRIRnErunNKk4spmnzU

# CSE 151B Final — Runs A–E at Scale (Group G049 "Chopped")

**Improving Mathematical Reasoning in Small Language Models (Qwen3-4B-Thinking)**

This notebook implements the future-work plan from our final presentation:

1. **Improve Run D** — clean GRPO implementation, tuned hyperparameters, checkpointing
2. **Finish Run E** — GRPO + LoRA, trained and evaluated end-to-end
3. **Re-run A–E on real data** — all five runs scored on the *same* held-out evaluation set
4. **Test majority voting at scale** — self-consistency with *diverse* samples (the milestone used
   near-deterministic sampling, which makes all votes identical — fixed here)

### What changed since the milestone
| Problem | Fix |
|---|---|
| 35 h for one pass over `public.jsonl` (HF loop, batch 1) | vLLM batched inference (~10–30× faster). HF fallback kept (`USE_VLLM=False`). |
| Results only saved at the very end → a crash lost everything | Results append to JSONL **after every chunk** and every run **resumes** where it left off. |
| GRPO run crashed before saving | Adapter checkpoints every 25 steps + incremental training log + resume. |
| `DATA_PATH` pointed at `private.jsonl` | Points at `public.jsonl`, split 80/20 into train/test. |
| A–C evaluated on questions GRPO would train on | All runs A–E score on the **same** stratified eval subset of the 20% *test* split — no contamination. |
| `\boxed{\frac{5}{8}}` extraction truncated at the first `}` | Brace-aware extractor (validated 1126/1126 on gold answers). |

## 1. Environment Setup

Installs pinned packages. vLLM brings its own torch build, so this takes ~5–8 min on a fresh
Kaggle session. **Restart the kernel after the first install**, then skip this cell on re-runs.

The `transformers<4.54` cap matters: vLLM 0.9.2 registers an `aimv2` model config, and
transformers ≥4.54 ships its own — importing vLLM then fails with
`ValueError: 'aimv2' is already used by a Transformers config`. If you ever see that error,
run `!pip install -q "transformers<4.54"` and restart the kernel.
"""

# Comment this cell out after the first successful install (then restart the kernel once).
!pip install -q "vllm==0.9.2" "transformers>=4.51.3,<4.54" "peft>=0.15.0" accelerate sympy antlr4-python3-runtime==4.11.1 pandas matplotlib tqdm

print("Dependencies installed — restart the kernel once after the first install.")

"""## 2. Configuration

All knobs live here. The defaults reproduce the experiments in our final report.

* `SMOKE_TEST=True` shrinks everything (8 eval questions, 4 GRPO prompts) so the whole notebook
  finishes in ~30 min and writes to `results/smoke/` — flip to `False` for the real runs.
* `RUN_A … RUN_E` let you execute one phase per Kaggle session; everything resumes from disk.
* The eval set is a **stratified 100-question subset of the 20% test split** so that A–C
  (inference-only) and D/E (trained on the 80% train split) are compared head-to-head with zero
  train/test contamination.
"""

import json, os, re, sys, gc, time, math, random, shutil
from pathlib import Path
from collections import Counter

os.environ["TOKENIZERS_PARALLELISM"] = "false"
os.environ.setdefault("VLLM_USE_V1", "0")          # V0 engine: stable on T4 (compute cap. 7.5)
os.environ.setdefault("PYTORCH_CUDA_ALLOC_CONF", "expandable_segments:True")

SEED = 151
random.seed(SEED)

MODEL_ID = "Qwen/Qwen3-4B-Thinking-2507"

# ── locate data (works on Kaggle and locally) ────────────────────────────────
def find_file(name):
    '''Pass a bare filename (searched recursively under /kaggle/input, ., ..)
    or an absolute path. Note: Kaggle datasets mount at /kaggle/input/<dataset-name>/,
    not at their web slug (e.g. /kaggle/input/inputs/public.jsonl).'''
    p = Path(name)
    if p.is_absolute():
        return p if p.exists() else None
    for root in [Path("/kaggle/input"), Path("."), Path("..")]:
        if root.exists():
            hits = sorted(root.glob(f"**/{name}"))
            if hits:
                return hits[0]
    return None

ON_KAGGLE    = Path("/kaggle/input").exists()
PUBLIC_PATH  = find_file("public.jsonl")
JUDGER_PATH  = find_file("judger.py")
assert PUBLIC_PATH is not None, "public.jsonl not found — attach the competition dataset."
print(f"public.jsonl : {PUBLIC_PATH}")
print(f"judger.py    : {JUDGER_PATH}")

# ── master switches ──────────────────────────────────────────────────────────
SMOKE_TEST  = True      # <<< flip to False for the real runs
RUN_A       = True
RUN_B       = True
RUN_C       = True
RUN_D       = True
RUN_E       = True

USE_VLLM        = True  # False -> slow HF transformers fallback (same interface)
TENSOR_PARALLEL = 1     # try 2 on T4x2 for extra speed (set 1 if vLLM init hangs)

# ── data split ───────────────────────────────────────────────────────────────
TEST_FRAC = 0.20        # 80% train (GRPO) / 20% test
EVAL_N    = 100         # stratified eval subset of the test split, shared by ALL runs
EVAL_FULL_TEST = False  # True: D/E also evaluated on the full 20% test split

# ── decoding ─────────────────────────────────────────────────────────────────
MAX_MODEL_LEN      = 8192
BASELINE_MAX_TOKENS = 4096   # Run A single-pass budget (starter default)
STEP1_TOKENS       = 1536    # two-step decoding: reasoning budget for runs B/C/D/E eval
NUM_VOTES          = 5       # Run C: samples per question for self-consistency

SAMPLING = {
    # Run A reproduces the starter notebook exactly (per-type sampling)
    "A_mcq":  dict(temperature=0.0, top_p=1.0,  top_k=0),
    "A_free": dict(temperature=0.3, top_p=0.95, top_k=0),
    # Runs B/D/E eval: our milestone's tuned near-deterministic sampling
    "tuned":  dict(temperature=0.1, top_p=0.1,  top_k=20),
    # Run C: self-consistency NEEDS diverse samples (milestone mistake fixed)
    "vote":   dict(temperature=0.7, top_p=0.95, top_k=20),
}

# ── GRPO ─────────────────────────────────────────────────────────────────────
GRPO_TRAIN_SIZE  = 150    # prompts sampled (stratified) from the 80% train split
GRPO_GROUP_SIZE  = 4      # Run E: completions per prompt (Run D uses 1)
GRPO_EPOCHS_D    = 2
GRPO_EPOCHS_E    = 1
GRPO_LR          = 2e-5
GRPO_TEMP        = 1.0    # rollout sampling temperature (exploration)
GRPO_STEP1_TOKENS = 320   # short reasoning budget keeps rollouts cheap
GRPO_BASELINE    = 0.5    # Run D fixed baseline (advantage = reward - 0.5)
SAVE_EVERY       = 25     # adapter checkpoint interval (steps)
LORA_R, LORA_ALPHA, LORA_DROPOUT = 16, 32, 0.05

# ── output dirs ──────────────────────────────────────────────────────────────
WORK_DIR   = Path("/kaggle/working") if ON_KAGGLE else Path(".")
OUTPUT_DIR = WORK_DIR / ("results/smoke" if SMOKE_TEST else "results")
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

if SMOKE_TEST:
    EVAL_N, NUM_VOTES = 8, 3
    GRPO_TRAIN_SIZE, GRPO_EPOCHS_D, GRPO_EPOCHS_E = 4, 1, 1
    STEP1_TOKENS, BASELINE_MAX_TOKENS = 512, 1024
    print("*** SMOKE TEST MODE — tiny sizes, results in", OUTPUT_DIR, "***")
print(f"Output dir: {OUTPUT_DIR.resolve()}")

# ── restore previous sessions' results (Kaggle wipes /kaggle/working) ─────────
# Workflow: at the end of a session click "Save Version"; in the next session add
# that notebook's *output* as an input dataset. This cell then copies prior
# results/adapters back into OUTPUT_DIR so every run resumes where it stopped.
def restore_previous_results():
    if not ON_KAGGLE:
        return
    patterns = ["run_*.jsonl", "*_train_log.jsonl"]
    restored = 0
    for src in Path("/kaggle/input").glob("**/results/**/*"):
        in_smoke = "smoke" in src.parts
        if in_smoke != SMOKE_TEST:
            continue
        if src.is_file() and any(src.match(p) for p in patterns):
            dst = OUTPUT_DIR / src.name
            if not dst.exists():
                shutil.copy(src, dst)
                restored += 1
        elif src.is_dir() and src.name.endswith("_adapter"):
            dst = OUTPUT_DIR / src.name
            if not dst.exists():
                shutil.copytree(src, dst)
                restored += 1
    if restored:
        print(f"Restored {restored} result file(s)/adapter(s) from previous sessions.")

restore_previous_results()

"""## 3. Data — Load `public.jsonl`, 80/20 Stratified Split

* Split is stratified by question type (MCQ vs free-form) with a fixed seed, so it is identical
  on every machine and every re-run.
* `train_split.jsonl` (~80%) is the GRPO training pool; `test_split.jsonl` (~20%) is held out.
* `eval_set.jsonl` is a stratified `EVAL_N`-question subset of the **test** split — every run
  A–E is scored on exactly these questions.
* Split files are saved next to the results for the report's reproducibility section.
"""

def load_jsonl(path):
    out = []
    with open(path, "r", encoding="utf-8") as f:
        for ln, line in enumerate(f, 1):
            line = line.strip()
            if not line:
                continue
            try:
                out.append(json.loads(line))
            except json.JSONDecodeError as e:
                print(f"Skipping malformed JSON on line {ln}: {e}")
    return out

data = load_jsonl(PUBLIC_PATH)

def stratified_split(items, test_frac, seed):
    rng = random.Random(seed)
    mcq  = [d for d in items if d.get("options")]
    free = [d for d in items if not d.get("options")]
    train, test = [], []
    for group in (mcq, free):
        idx = list(range(len(group)))
        rng.shuffle(idx)
        n_test = round(len(group) * test_frac)
        test  += [group[i] for i in idx[:n_test]]
        train += [group[i] for i in idx[n_test:]]
    train.sort(key=lambda d: d["id"]); test.sort(key=lambda d: d["id"])
    return train, test

def stratified_take(items, n, seed):
    rng = random.Random(seed)
    mcq  = [d for d in items if d.get("options")]
    free = [d for d in items if not d.get("options")]
    n = min(n, len(items))
    n_mcq = min(len(mcq), round(n * len(mcq) / len(items)))
    take = rng.sample(mcq, n_mcq) + rng.sample(free, n - n_mcq)
    take.sort(key=lambda d: d["id"])
    return take

train_items, test_items = stratified_split(data, TEST_FRAC, SEED)
eval_items = stratified_take(test_items, EVAL_N, SEED)

def save_jsonl(items, path):
    with open(path, "w", encoding="utf-8") as f:
        for d in items:
            f.write(json.dumps(d) + "\n")

save_jsonl(train_items, OUTPUT_DIR / "train_split.jsonl")
save_jsonl(test_items,  OUTPUT_DIR / "test_split.jsonl")
save_jsonl(eval_items,  OUTPUT_DIR / "eval_set.jsonl")

def describe(name, items):
    n_mcq = sum(bool(d.get("options")) for d in items)
    print(f"{name:<12} {len(items):>5} questions ({n_mcq} MCQ, {len(items)-n_mcq} free-form)")

describe("full public", data)
describe("train (80%)", train_items)
describe("test  (20%)", test_items)
describe("eval subset", eval_items)

"""## 4. Prompts — Baseline (Run A) and Tuned + Few-Shot (Runs B–E)"""

# ── starter prompts (Run A), verbatim ────────────────────────────────────────
SYSTEM_PROMPT_MATH = (
    "You are an expert mathematician. Solve the problem step-by-step, showing your reasoning briefly. "
    "Put your final answer inside \\boxed{}. "
    "If the problem has multiple sub-answers, separate them by commas inside a single \\boxed{}, "
    "e.g. \\boxed{3, 7}.\n\n"
    "Keep your response concise and ensure the boxed answer appears early.\n\n"
    "Example:\n"
    "Question: What is 2 + 3?\n"
    "Reasoning: Adding 2 and 3 gives 5.\n"
    "\\boxed{5}"
)

SYSTEM_PROMPT_MCQ = (
    "You are an expert mathematician. "
    "Read the problem and the answer choices below, then select the single best answer. "
    "Output ONLY the letter of your chosen option inside \\boxed{}, e.g. \\boxed{C}. "
    "Do not include any explanation or additional text.\n\n"
    "Keep your response concise.\n\n"
    "Example:\n"
    "Question: What is 2 + 2?\n"
    "Options:\n"
    "A. 3\n"
    "B. 4\n"
    "C. 5\n"
    "\\boxed{B}"
)

# ── tuned prompts + few-shot (Runs B, C, and D/E training & eval) ─────────────
TUNED_SYSTEM_MATH = (
    "You are an expert competition mathematician. Solve the problem efficiently:\n"
    "1. Read the problem once and identify exactly what is asked.\n"
    "2. Solve it with short, direct reasoning. Do NOT re-derive or re-verify a result you "
    "already obtained; one careful pass is enough.\n"
    "3. End with the final answer inside a single \\boxed{}.\n\n"
    "Answer format rules:\n"
    "- If the problem contains several blanks ([ANS]) or sub-questions, give one value per blank, "
    "in order, separated by commas inside ONE \\boxed{}, e.g. \\boxed{3, 7, 1/2}.\n"
    "- Give exact values (fractions like 5/8, expressions like (n+2)/(n+4)) when the problem is "
    "exact; otherwise round decimal answers to exactly 6 decimal places (e.g. 2.326248).\n"
    "- Never include units, words, or '$' inside \\boxed{} unless the blank asks for a word "
    "(e.g. Yes/No).\n\n"
    "Example 1:\n"
    "Question: Reduce the fraction 25/40. [ANS]\n"
    "Reasoning: gcd(25, 40) = 5, so 25/40 = 5/8.\n"
    "\\boxed{5/8}\n\n"
    "Example 2:\n"
    "Question: A candle melts at 145 F. Convert: [ANS] Celsius, [ANS] Kelvin.\n"
    "Reasoning: C = (145-32)*5/9 = 62.777778. K = C + 273.15 = 335.927778.\n"
    "\\boxed{62.777778, 335.927778}"
)

TUNED_SYSTEM_MCQ = (
    "You are an expert competition mathematician answering a multiple-choice question.\n"
    "1. Solve the problem directly first, with short reasoning.\n"
    "2. Pick the option matching your result. Do NOT exhaustively disprove every other option, "
    "and do NOT re-verify your computation more than once.\n"
    "3. Output ONLY the option letter inside \\boxed{}.\n\n"
    "Example 1:\n"
    "Question: What is 6 * 7?  Options: A. 41  B. 42  C. 43\n"
    "Reasoning: 6*7 = 42, which is option B.\n"
    "\\boxed{B}\n\n"
    "Example 2:\n"
    "Question: d/dx of x^3?  Options: A. 3x^2  B. x^2  C. 3x\n"
    "Reasoning: The power rule gives 3x^2, option A.\n"
    "\\boxed{A}"
)

def build_prompt(item, style):
    '''Return (system, user) for a question. style in {'baseline', 'tuned'}.'''
    question, options = item["question"], item.get("options")
    if options:
        labels = [chr(65 + i) for i in range(len(options))]
        opts = "\n".join(f"{l}. {str(o).strip()}" for l, o in zip(labels, options))
        user = f"{question}\n\nOptions:\n{opts}"
        system = SYSTEM_PROMPT_MCQ if style == "baseline" else TUNED_SYSTEM_MCQ
    else:
        user = question
        system = SYSTEM_PROMPT_MATH if style == "baseline" else TUNED_SYSTEM_MATH
        if style == "tuned":
            n_blanks = item["question"].count("[ANS]")
            if n_blanks > 1:
                user += (f"\n\n(This problem has {n_blanks} blanks — give exactly "
                         f"{n_blanks} comma-separated values in one \\boxed{{}}.)")
    return system, user

"""## 5. Scoring — `judger.py` with a Validated Fallback"""

# ===== scoring library (validated offline: 1126/1126 gold round-trip) =====
"""Answer extraction + fallback judging for the CSE 151B math competition.

This module is embedded into the final notebook. It is tested locally by
feeding gold answers back in as predictions (should score ~100%).

Two pieces:
  1. extract_boxed(text)      - brace-aware \boxed{...} extraction (handles \frac{a}{b})
  2. FallbackJudger.judge()   - numeric/symbolic equivalence vs. gold answer list

The competition's judger.py is preferred when available; this is the fallback
so local runs (and crashed-session reruns) can still score.
"""
import re
from fractions import Fraction


# ── 1. boxed extraction ──────────────────────────────────────────────────────

def extract_boxed(text: str) -> str:
    """Return content of the LAST \\boxed{...} in text, brace-aware.

    The starter regex r'\\boxed\\{([^}]+)\\}' truncates nested braces like
    \\boxed{\\frac{5}{8}} -> '\\frac{5'. This walks braces properly.
    """
    if not text:
        return ""
    out = ""
    for m in re.finditer(r"\\boxed\s*\{", text):
        depth = 1
        i = m.end()
        start = i
        while i < len(text) and depth > 0:
            if text[i] == "{":
                depth += 1
            elif text[i] == "}":
                depth -= 1
            i += 1
        if depth == 0:
            out = text[start:i - 1].strip()
    return out


def split_top_level_commas(s: str) -> list:
    """Split a multi-part boxed answer '3, 7' on commas not inside (), [], {}."""
    parts, depth, cur = [], 0, []
    for ch in s:
        if ch in "([{":
            depth += 1
        elif ch in ")]}":
            depth -= 1
        if ch == "," and depth == 0:
            parts.append("".join(cur).strip())
            cur = []
        else:
            cur.append(ch)
    if cur:
        parts.append("".join(cur).strip())
    return [p for p in parts if p]


def extract_mcq_letter(text: str, n_options: int = 26) -> str:
    """Extract an MCQ letter, preferring the boxed answer."""
    boxed = extract_boxed(text)
    if boxed:
        m = re.search(r"[A-Za-z]", boxed)
        if m and len(boxed.strip()) <= 3:
            return m.group(0).upper()
        # boxed contains a full expression; fall through to scan
    matches = re.findall(r"\b([A-Z])\b", text.upper())
    return matches[-1] if matches else ""


# ── 2. fallback judging ──────────────────────────────────────────────────────

_LATEX_REPLACEMENTS = [
    (r"\\left", ""), (r"\\right", ""), (r"\\!", ""), (r"\\,", ""), (r"\\;", ""),
    (r"\\mathrm\{([^}]*)\}", r"\1"), (r"\\text\{([^}]*)\}", r"\1"),
    (r"\\dfrac", r"\\frac"), (r"\\tfrac", r"\\frac"),
    (r"\\cdot", "*"), (r"\\times", "*"), (r"\\div", "/"),
    (r"\\pi", "pi"), (r"\\infty", "oo"),
    (r"\$", ""), (r"\\%", ""), (r"%", ""), (r"\\\$", ""),
    (r"\\ ", " "),
]


def _latex_to_plain(s: str) -> str:
    s = s.strip()
    for pat, rep in _LATEX_REPLACEMENTS:
        s = re.sub(pat, rep, s)
    # \frac{a}{b} -> (a)/(b), applied repeatedly for nesting
    frac = re.compile(r"\\frac\s*\{([^{}]*)\}\s*\{([^{}]*)\}")
    while frac.search(s):
        s = frac.sub(r"((\1)/(\2))", s)
    # \sqrt{a} -> sqrt(a)
    sqrt = re.compile(r"\\sqrt\s*\{([^{}]*)\}")
    while sqrt.search(s):
        s = sqrt.sub(r"sqrt(\1)", s)
    s = s.replace("^", "**").replace("{", "(").replace("}", ")")
    s = s.replace("−", "-")  # unicode minus
    return s.strip()


def _to_number(s: str):
    """Best-effort numeric value of a string, else None."""
    s = s.strip().rstrip(".")
    s = s.replace(",", "")  # 1,000 -> 1000
    try:
        return float(s)
    except ValueError:
        pass
    try:
        return float(Fraction(s))
    except (ValueError, ZeroDivisionError):
        pass
    plain = _latex_to_plain(s)
    try:
        import sympy
        val = sympy.sympify(plain, rational=False)
        if val.is_number:
            return float(val.evalf())
    except Exception:
        pass
    return None


def _norm_str(s: str) -> str:
    s = s.strip().lower()
    s = re.sub(r"\s+", "", s)
    s = s.rstrip(".")
    return s


class FallbackJudger:
    """Numeric/symbolic equivalence judging when the official judger.py is absent.

    Numeric tolerance mirrors the official judger's behavior (verified against
    judger.py): gold is rounded to 6 decimal places and the prediction must match
    it to ~1e-8 relative error. So '143.224229' passes against gold
    '143.224229233795' but '143.224' does not.
    """

    def __init__(self, rel_tol: float = 1.01e-8):
        self.rel_tol = rel_tol

    def parts_equal(self, pred: str, gold: str) -> bool:
        if not pred:
            return False
        # exact normalized string match (covers 'No', '5/8', text answers)
        if _norm_str(pred) == _norm_str(gold):
            return True
        # numeric comparison, mimicking the official judger's gold-rounding rule
        pv, gv = _to_number(pred), _to_number(gold)
        if pv is not None and gv is not None:
            gv6 = round(gv, 6)
            denom = abs(gv6) if gv6 != 0 else 1.0
            if abs(pv - gv6) / denom <= self.rel_tol:
                return True
            # full-precision exact match (official accepts these via string/N() paths)
            return abs(pv - gv) <= 1e-12 * max(1.0, abs(gv))
        # symbolic comparison via sympy
        try:
            import sympy
            pe = sympy.sympify(_latex_to_plain(pred))
            ge = sympy.sympify(_latex_to_plain(gold))
            if sympy.simplify(pe - ge) == 0:
                return True
        except Exception:
            pass
        return False

    def judge(self, pred_text: str, gold) -> bool:
        """pred_text: raw model response. gold: answer list (or single string)."""
        gold_list = gold if isinstance(gold, list) else [gold]
        boxed = extract_boxed(pred_text)
        if not boxed:
            return False
        parts = split_top_level_commas(boxed)
        if len(gold_list) == 1:
            # allow the whole boxed string OR its single part to match
            cands = [boxed] + parts
            return any(self.parts_equal(c, str(gold_list[0])) for c in cands)
        if len(parts) != len(gold_list):
            return False
        return all(self.parts_equal(p, str(g)) for p, g in zip(parts, gold_list))

# ── judging wrapper: official judger if available, validated fallback otherwise
import signal as _signal

HAS_OFFICIAL = False
# judger.auto_judge uses signal.SIGALRM, which only exists on Linux (Kaggle is
# fine). On Windows we skip it and use the fallback, which mirrors its tolerance.
if JUDGER_PATH is not None and hasattr(_signal, "SIGALRM"):
    sys.path.insert(0, str(JUDGER_PATH.parent))   # also makes `import utils` work
    try:
        from judger import Judger
        OFFICIAL_JUDGER = Judger(strict_extract=False)
        HAS_OFFICIAL = True
        print("Using official judger.py")
    except Exception as exc:
        print("judger.py import failed, using fallback:", exc)
elif JUDGER_PATH is not None:
    print("judger.py found, but no SIGALRM on this OS (Windows) -> fallback judger; "
          "Kaggle runs will use the official judger.")
FALLBACK_JUDGER = FallbackJudger()
if not HAS_OFFICIAL:
    print("Using validated fallback judger")

def judge_item(item, response):
    '''True iff the model response answers `item` correctly.'''
    if item.get("options"):
        return extract_mcq_letter(response) == str(item["answer"]).strip().upper()
    gold = item["answer"]
    gold_list = gold if isinstance(gold, list) else [gold]
    if HAS_OFFICIAL:
        try:
            return bool(OFFICIAL_JUDGER.auto_judge(
                pred=response, gold=gold_list, options=[[]] * len(gold_list)))
        except Exception:
            pass
    return FALLBACK_JUDGER.judge(response, gold_list)

def vote_key(item, response):
    '''Normalized answer string used to bucket votes for self-consistency.'''
    if item.get("options"):
        return extract_mcq_letter(response)
    return re.sub(r"\s+", "", extract_boxed(response)).lower()

"""## 6. Inference Engine — vLLM (primary) / HF transformers (fallback)

One interface, two backends:

* `generate_batch(prompts, ...)` → `list[list[str]]` (n completions per prompt)
* `two_step(prompts, ...)` — our presentation's early-stopping trick: generate a bounded chunk of
  reasoning (step 1); if no `\boxed{}` appeared, append *"…the final answer is: \boxed{"* and
  greedy-decode the answer (step 2). This caps over-thinking, the model's main failure mode.

"""

from transformers import AutoTokenizer

TOKENIZER = AutoTokenizer.from_pretrained(MODEL_ID, trust_remote_code=True)
if TOKENIZER.pad_token is None:
    TOKENIZER.pad_token = TOKENIZER.eos_token

ANSWER_HINT = ("\n\nTime is up. Based on my reasoning above, "
               "the most likely final answer is: \\boxed{")

def chat_prompt(item, style):
    system, user = build_prompt(item, style)
    return TOKENIZER.apply_chat_template(
        [{"role": "system", "content": system}, {"role": "user", "content": user}],
        tokenize=False, add_generation_prompt=True)

# ── vLLM backend ─────────────────────────────────────────────────────────────
_VLLM = None
_VLLM_PATH = None

def load_vllm(model_path=MODEL_ID):
    global _VLLM, _VLLM_PATH
    if _VLLM is not None and _VLLM_PATH == str(model_path):
        return _VLLM
    if _VLLM is not None:          # different weights requested -> reload
        unload_vllm()
    from vllm import LLM
    _VLLM = LLM(model=str(model_path), dtype="float16", max_model_len=MAX_MODEL_LEN,
                gpu_memory_utilization=0.90, max_num_seqs=16, enforce_eager=True,
                tensor_parallel_size=TENSOR_PARALLEL, seed=SEED, trust_remote_code=True)
    _VLLM_PATH = str(model_path)
    return _VLLM

def unload_vllm():
    global _VLLM, _VLLM_PATH
    if _VLLM is None:
        return
    try:
        from vllm.distributed.parallel_state import (destroy_model_parallel,
                                                     destroy_distributed_environment)
        destroy_model_parallel(); destroy_distributed_environment()
    except Exception:
        pass
    del _VLLM
    _VLLM = None
    _VLLM_PATH = None
    gc.collect()
    import torch
    torch.cuda.empty_cache()
    print("vLLM unloaded, GPU memory freed.")

def _vllm_generate(prompts, *, temperature, top_p, top_k, max_tokens, n=1, stop=None):
    from vllm import SamplingParams
    kw = dict(temperature=float(temperature), top_p=float(top_p),
              max_tokens=int(max_tokens), n=int(n))
    if top_k and top_k > 0:
        kw["top_k"] = int(top_k)
    if stop:
        kw["stop"] = stop
    outs = load_vllm().generate(prompts, SamplingParams(**kw))
    return [[o.text for o in out.outputs] for out in outs]

# ── HF transformers backend (slow fallback, identical interface) ─────────────
_HF = None

def _hf_generate(prompts, *, temperature, top_p, top_k, max_tokens, n=1, stop=None):
    global _HF
    import torch
    from transformers import AutoModelForCausalLM
    if _HF is None:
        _HF = AutoModelForCausalLM.from_pretrained(
            MODEL_ID, torch_dtype=torch.float16, device_map="cuda:0",
            low_cpu_mem_usage=True, trust_remote_code=True)
        _HF.eval()
    results = []
    for p in prompts:
        ids = TOKENIZER(p, return_tensors="pt", add_special_tokens=False).input_ids.to(_HF.device)
        kw = dict(max_new_tokens=int(max_tokens), pad_token_id=TOKENIZER.eos_token_id,
                  num_return_sequences=int(n))
        if temperature and temperature > 0:
            kw.update(do_sample=True, temperature=float(temperature), top_p=float(top_p))
            if top_k and top_k > 0:
                kw["top_k"] = int(top_k)
        else:
            kw.update(do_sample=False)
        with torch.inference_mode():
            out = _HF.generate(ids, **kw)
        texts = [TOKENIZER.decode(seq[ids.shape[1]:], skip_special_tokens=True) for seq in out]
        if stop:
            texts = [t.split(stop[0])[0] for t in texts]
        results.append(texts)
    return results

def generate_batch(prompts, **kw):
    return _vllm_generate(prompts, **kw) if USE_VLLM else _hf_generate(prompts, **kw)

# ── two-step early-stopping decoder ──────────────────────────────────────────
def two_step(prompts, *, temperature, top_p, top_k, step1_tokens, n=1):
    '''Returns list[list[str]]: n final response texts per prompt.'''
    step1 = generate_batch(prompts, temperature=temperature, top_p=top_p, top_k=top_k,
                           max_tokens=step1_tokens, n=n)
    flat_prompts, flat_texts = [], []
    for p, outs in zip(prompts, step1):
        for t in outs:
            flat_prompts.append(p)
            flat_texts.append(t)
    need = [i for i, t in enumerate(flat_texts) if not extract_boxed(t)]
    if need:
        cont = [flat_prompts[i] + flat_texts[i] + ANSWER_HINT for i in need]
        step2 = generate_batch(cont, temperature=0.0, top_p=1.0, top_k=0,
                               max_tokens=32, n=1, stop=["}"])
        for i, s2 in zip(need, step2):
            ans = s2[0].split("}")[0].strip()
            flat_texts[i] = flat_texts[i] + ANSWER_HINT + ans + "}"
    out, k = [], 0
    for _ in prompts:
        out.append(flat_texts[k:k + n])
        k += n
    return out

"""## 7. Experiment Runner — Incremental Saving + Resume

The milestone's biggest operational failure was losing a 30+ hour run because results were only
written at the end. `run_experiment` therefore:

* appends scored records to `results/run_<NAME>.jsonl` **after every chunk** (~24 questions),
* on restart, **skips question ids already in the file** (crash-safe resume),
* prints running accuracy so a dying session still tells you where you stand.
"""

def _load_done_ids(path):
    if not Path(path).exists():
        return set()
    return {json.loads(l)["id"] for l in open(path, encoding="utf-8") if l.strip()}

def _append_records(path, records):
    with open(path, "a", encoding="utf-8") as f:
        for r in records:
            f.write(json.dumps(r) + "\n")
        f.flush()
        os.fsync(f.fileno())

def _chunks(seq, size):
    for i in range(0, len(seq), size):
        yield seq[i:i + size]

def run_experiment(run_name, items, *, style, mode, sampling, max_tokens=None,
                   n_votes=1, chunk_size=24):
    '''mode: 'single' (one-pass), 'two_step', or 'vote' (two_step x n_votes + majority).'''
    out_path = OUTPUT_DIR / f"run_{run_name}.jsonl"
    done = _load_done_ids(out_path)
    todo = [it for it in items if it["id"] not in done]
    print(f"[{run_name}] {len(done)} already done, {len(todo)} to go -> {out_path}")
    n_correct = sum(json.loads(l)["correct"] for l in open(out_path, encoding="utf-8")) if done else 0
    n_total = len(done)
    n_session = 0
    t0 = time.time()
    for chunk in _chunks(todo, chunk_size):
        prompts = [chat_prompt(it, style) for it in chunk]
        records = []
        if mode == "single":
            texts = generate_batch(prompts, **sampling, max_tokens=max_tokens, n=1)
            responses = [t[0] for t in texts]
            votes_per_item = [None] * len(chunk)
        elif mode == "two_step":
            texts = two_step(prompts, **sampling, step1_tokens=STEP1_TOKENS, n=1)
            responses = [t[0] for t in texts]
            votes_per_item = [None] * len(chunk)
        elif mode == "vote":
            texts = two_step(prompts, **sampling, step1_tokens=STEP1_TOKENS, n=n_votes)
            responses, votes_per_item = [], []
            for it, cands in zip(chunk, texts):
                keys = [vote_key(it, c) for c in cands]
                valid = [k for k in keys if k]
                winner = Counter(valid).most_common(1)[0][0] if valid else ""
                rep = next((c for c, k in zip(cands, keys) if k == winner), cands[0])
                responses.append(rep)
                votes_per_item.append(keys)
        else:
            raise ValueError(mode)
        for it, resp, votes in zip(chunk, responses, votes_per_item):
            ok = bool(judge_item(it, resp))
            rec = {"id": it["id"], "is_mcq": bool(it.get("options")), "gold": it["answer"],
                   "response": resp, "pred": extract_boxed(resp), "correct": ok,
                   "n_words": len(resp.split()), "run": run_name}
            if votes is not None:
                rec["votes"] = votes
            records.append(rec)
            n_correct += ok
            n_total += 1
            n_session += 1
        _append_records(out_path, records)
        rate = n_session / max(time.time() - t0, 1e-9)
        print(f"[{run_name}] {n_total}/{len(items)} scored | "
              f"running acc {100.0*n_correct/max(n_total,1):.1f}% | "
              f"{rate:.2f} q/s this session")
    print(f"[{run_name}] DONE — accuracy {100.0*n_correct/max(n_total,1):.2f}% "
          f"({n_correct}/{n_total})")
    return out_path

"""## 8. Runs A, B, C (inference-only)

Estimated time on T4 with vLLM (100 questions,
`SMOKE_TEST=False`): A ≈ 20–30 min, B ≈ 10–20 min, C ≈ 45–75 min.

* **A — starter baseline**: starter prompts, starter sampling, single-pass decode.
* **B — tuned prompt + few-shot + two-step decode**: tuned sampling (T=0.1, top-p=0.1, top-k=20).
* **C — majority voting at scale**: tuned prompt, **diverse** sampling (T=0.7, top-p=0.95),
  5 votes, most frequent boxed answer wins (self-consistency, Wang et al. 2023).
"""

if RUN_A or RUN_B or RUN_C:
    load_vllm() if USE_VLLM else None

if RUN_A:
    mcq_items  = [d for d in eval_items if d.get("options")]
    free_items = [d for d in eval_items if not d.get("options")]
    run_experiment("A", mcq_items,  style="baseline", mode="single",
                   sampling=SAMPLING["A_mcq"],  max_tokens=BASELINE_MAX_TOKENS)
    run_experiment("A", free_items, style="baseline", mode="single",
                   sampling=SAMPLING["A_free"], max_tokens=BASELINE_MAX_TOKENS)

if RUN_B:
    run_experiment("B", eval_items, style="tuned", mode="two_step",
                   sampling=SAMPLING["tuned"])

if RUN_C:
    run_experiment("C", eval_items, style="tuned", mode="vote",
                   sampling=SAMPLING["vote"], n_votes=NUM_VOTES)

"""### Interim summary (A–C)"""

import pandas as pd

def summarize(run_names):
    rows = []
    for name in run_names:
        path = OUTPUT_DIR / f"run_{name}.jsonl"
        if not path.exists():
            continue
        recs = [json.loads(l) for l in open(path, encoding="utf-8") if l.strip()]
        if not recs:
            continue
        mcq  = [r for r in recs if r["is_mcq"]]
        free = [r for r in recs if not r["is_mcq"]]
        acc = lambda rs: 100.0 * sum(r["correct"] for r in rs) / len(rs) if rs else float("nan")
        rows.append({"run": name, "n": len(recs),
                     "accuracy_%": round(acc(recs), 2),
                     "mcq_acc_%": round(acc(mcq), 2),
                     "free_acc_%": round(acc(free), 2),
                     "avg_words": round(sum(r["n_words"] for r in recs) / len(recs), 1)})
    return pd.DataFrame(rows)

summary_abc = summarize(["A", "B", "C"])
print(summary_abc.to_string(index=False))

"""## 9. GRPO Fine-Tuning (Runs D and E)

**Free GPU memory first** — the next cell unloads vLLM. On a T4×2 the policy trains on `cuda:1`
while GPU 0 stays clean; on a single GPU the unload below is required.

### What D and E are
Both runs do reinforcement fine-tuning with a binary correctness reward on prompts from the
**80% train split** (`GRPO_TRAIN_SIZE` prompts, stratified). Rollouts use the two-step decoder
with a short reasoning budget; the policy gradient flows through the *sampled reasoning tokens*.

* **Run D (milestone GRPO, improved)** — 1 sample/prompt, fixed-baseline advantage
  `A = r − 0.5` (exactly the estimator we presented), now with checkpointing, correct loss
  masking, gradient clipping, and 2 epochs.
* **Run E (GRPO + LoRA, finished)** — group-relative advantage over `G=4` samples/prompt:
  `A_i = (r_i − mean(r)) / std(r)` (Shao et al., 2024). Groups where every sample gets the same
  reward are skipped (zero advantage).

Both update LoRA adapters (r=16, α=32 on q/v projections, dropout 0.05, lr 2e-5) — full-parameter
RL on a 4B model does not fit in T4 memory, so the runs differ **only in the advantage
estimator and group size**, which is the comparison we care about.

Reward: `1.0` correct · `0.1` well-formed `\boxed{}` but wrong · `0.0` no boxed answer.
The 0.1 format-shaping term keeps the gradient alive early, when correct answers are rare.

Crash-safety: adapter checkpoint + training log every `SAVE_EVERY` steps; rerunning the cell
resumes from the last checkpoint and skips logged steps.
"""

if RUN_D or RUN_E:
    unload_vllm()

    import torch
    from torch.optim import AdamW
    from transformers import AutoModelForCausalLM
    from peft import LoraConfig, get_peft_model, PeftModel

    GRPO_DEVICE = "cuda:1" if torch.cuda.device_count() > 1 else "cuda:0"
    print("GRPO trains on", GRPO_DEVICE)

    def load_policy(resume_dir=None):
        base = AutoModelForCausalLM.from_pretrained(
            MODEL_ID, torch_dtype=torch.float16, device_map=GRPO_DEVICE,
            low_cpu_mem_usage=True, trust_remote_code=True)
        base.config.pad_token_id = TOKENIZER.eos_token_id
        if resume_dir is not None and Path(resume_dir).exists():
            print("Resuming adapter from", resume_dir)
            model = PeftModel.from_pretrained(base, resume_dir, is_trainable=True)
        else:
            lcfg = LoraConfig(r=LORA_R, lora_alpha=LORA_ALPHA,
                              target_modules=["q_proj", "v_proj"],
                              lora_dropout=LORA_DROPOUT, bias="none",
                              task_type="CAUSAL_LM")
            model = get_peft_model(base, lcfg)
        model.enable_input_require_grads()
        model.gradient_checkpointing_enable(
            gradient_checkpointing_kwargs={"use_reentrant": False})
        for p in model.parameters():            # fp32 master copies of LoRA params
            if p.requires_grad:
                p.data = p.data.float()
        model.print_trainable_parameters()
        return model

    def grpo_reward(item, response_text):
        if judge_item(item, response_text):
            return 1.0
        return 0.1 if extract_boxed(response_text) else 0.0

    @torch.no_grad()
    def grpo_rollout(model, item, n_samples):
        '''Sample n responses with the two-step decoder. Returns list of dicts.'''
        # eval() is required: in train mode, gradient checkpointing disables the KV
        # cache and generation becomes quadratically slow.
        model.eval()
        prompt = chat_prompt(item, style="tuned")
        ids = TOKENIZER(prompt, return_tensors="pt",
                        add_special_tokens=False).input_ids.to(GRPO_DEVICE)
        with torch.autocast("cuda", dtype=torch.float16):
            out = model.generate(
                ids, do_sample=True, temperature=GRPO_TEMP, top_p=0.95, top_k=50,
                max_new_tokens=GRPO_STEP1_TOKENS, num_return_sequences=n_samples,
                pad_token_id=TOKENIZER.eos_token_id)
        samples = []
        hint_ids = TOKENIZER(ANSWER_HINT, return_tensors="pt",
                             add_special_tokens=False).input_ids.to(GRPO_DEVICE)
        for k in range(n_samples):
            gen = out[k, ids.shape[1]:]
            gen = gen[gen != TOKENIZER.eos_token_id]      # strip right padding
            text = TOKENIZER.decode(gen, skip_special_tokens=True)
            full_text = text
            if not extract_boxed(text):                   # step 2: inject answer hint
                ctx = torch.cat([ids[0], gen, hint_ids[0]]).unsqueeze(0)
                with torch.autocast("cuda", dtype=torch.float16):
                    ans = model.generate(ctx, do_sample=False, max_new_tokens=24,
                                         pad_token_id=TOKENIZER.eos_token_id)
                ans_text = TOKENIZER.decode(ans[0, ctx.shape[1]:],
                                            skip_special_tokens=True).split("}")[0]
                full_text = text + ANSWER_HINT + ans_text + "}"
            samples.append({"prompt_ids": ids[0], "gen_ids": gen, "text": full_text})
        return samples

    def grpo_update(model, optimizer, scaler, samples, advantages):
        '''One policy-gradient step over a group. Loss masked to sampled reasoning tokens.'''
        optimizer.zero_grad(set_to_none=True)
        n_active, total_loss = 0, 0.0
        for s, adv in zip(samples, advantages):
            if abs(adv) < 1e-8 or s["gen_ids"].numel() == 0:
                continue
            seq = torch.cat([s["prompt_ids"], s["gen_ids"]]).unsqueeze(0)
            p_len = s["prompt_ids"].shape[0]
            with torch.autocast("cuda", dtype=torch.float16):
                logits = model(seq, use_cache=False).logits
            logp = torch.log_softmax(logits[0, :-1].float(), dim=-1)
            tgt = seq[0, 1:]
            tok_logp = logp.gather(1, tgt.unsqueeze(1)).squeeze(1)
            gen_logp = tok_logp[p_len - 1:]               # logprobs of generated tokens
            loss = -(adv * gen_logp.mean()) / len(samples)
            scaler.scale(loss).backward()
            total_loss += float(loss.detach())
            n_active += 1
        if n_active == 0:
            return None
        scaler.unscale_(optimizer)
        torch.nn.utils.clip_grad_norm_(
            [p for p in model.parameters() if p.requires_grad], 1.0)
        scaler.step(optimizer)
        scaler.update()
        return total_loss

    def train_grpo(run_name, *, mode, group_size, epochs, train_pool):
        '''mode='fixed' (Run D, A = r - 0.5) or 'group' (Run E, group-relative).'''
        ckpt_dir = OUTPUT_DIR / f"{run_name}_adapter"
        log_path = OUTPUT_DIR / f"{run_name}_train_log.jsonl"
        prompts = stratified_take(train_pool, GRPO_TRAIN_SIZE, SEED + 7)
        schedule = []
        for ep in range(epochs):
            order = list(prompts)
            random.Random(SEED + ep).shuffle(order)
            schedule += order
        done_steps = sum(1 for _ in open(log_path, encoding="utf-8")) if log_path.exists() else 0
        print(f"[{run_name}] {len(schedule)} total steps, resuming at step {done_steps}")
        model = load_policy(resume_dir=ckpt_dir if done_steps > 0 else None)
        model.train()
        optimizer = AdamW([p for p in model.parameters() if p.requires_grad], lr=GRPO_LR)
        scaler = torch.amp.GradScaler("cuda")
        recent_rewards = []
        t0 = time.time()
        for step, item in enumerate(schedule):
            if step < done_steps:
                continue
            samples = grpo_rollout(model, item, group_size)
            rewards = [grpo_reward(item, s["text"]) for s in samples]
            if mode == "fixed":
                advantages = [r - GRPO_BASELINE for r in rewards]
            else:
                mu = sum(rewards) / len(rewards)
                sd = (sum((r - mu) ** 2 for r in rewards) / len(rewards)) ** 0.5
                advantages = [0.0] * len(rewards) if sd < 1e-6 else \
                             [(r - mu) / (sd + 1e-4) for r in rewards]
            model.train()
            loss = grpo_update(model, optimizer, scaler, samples, advantages)
            recent_rewards += rewards
            with open(log_path, "a", encoding="utf-8") as f:
                f.write(json.dumps({"step": step, "id": item["id"], "rewards": rewards,
                                    "loss": loss,
                                    "gen_tokens": [int(s["gen_ids"].shape[0]) for s in samples]
                                    }) + "\n")
            if (step + 1) % SAVE_EVERY == 0 or step == len(schedule) - 1:
                model.save_pretrained(ckpt_dir)
                window = recent_rewards[-SAVE_EVERY * group_size:]
                print(f"[{run_name}] step {step+1}/{len(schedule)} | "
                      f"mean reward (last {len(window)}) {sum(window)/max(len(window),1):.3f} | "
                      f"{(time.time()-t0)/60:.1f} min | checkpoint saved")
        model.save_pretrained(ckpt_dir)
        print(f"[{run_name}] training complete -> {ckpt_dir}")
        del model, optimizer
        gc.collect()
        torch.cuda.empty_cache()
        return ckpt_dir

"""### Train Run D (fixed-baseline GRPO, 1 sample/prompt)"""

if RUN_D:
    train_grpo("D", mode="fixed", group_size=1, epochs=GRPO_EPOCHS_D,
               train_pool=train_items)

"""### Train Run E (group-relative GRPO + LoRA, 4 samples/prompt)"""

if RUN_E:
    train_grpo("E", mode="group", group_size=GRPO_GROUP_SIZE, epochs=GRPO_EPOCHS_E,
               train_pool=train_items)

"""## 10. Evaluate D and E on the Held-Out Eval Set

"""

def merge_adapter(adapter_dir, merged_dir):
    import torch
    from transformers import AutoModelForCausalLM
    from peft import PeftModel
    print(f"Merging {adapter_dir} -> {merged_dir} (CPU)...")
    base = AutoModelForCausalLM.from_pretrained(
        MODEL_ID, torch_dtype=torch.float16, device_map="cpu",
        low_cpu_mem_usage=True, trust_remote_code=True)
    merged = PeftModel.from_pretrained(base, adapter_dir).merge_and_unload()
    merged.save_pretrained(merged_dir, safe_serialization=True)
    TOKENIZER.save_pretrained(merged_dir)
    del base, merged
    gc.collect()

def eval_finetuned(run_name, eval_pool):
    adapter_dir = OUTPUT_DIR / f"{run_name}_adapter"
    assert adapter_dir.exists(), f"no adapter at {adapter_dir} — train first"
    merged_dir = WORK_DIR / f"{run_name}_merged"
    if not (merged_dir / "config.json").exists():
        merge_adapter(adapter_dir, merged_dir)
    unload_vllm()
    global _VLLM
    load_vllm(merged_dir)
    run_experiment(run_name, eval_pool, style="tuned", mode="two_step",
                   sampling=SAMPLING["tuned"])
    unload_vllm()
    shutil.rmtree(merged_dir, ignore_errors=True)
    print(f"[{run_name}] eval done, merged copy removed.")

if RUN_D:
    eval_finetuned("D", test_items if EVAL_FULL_TEST else eval_items)

if RUN_E:
    eval_finetuned("E", test_items if EVAL_FULL_TEST else eval_items)

"""## 11. Final Results — Table, Plots, and Report Artifacts

"""

import pandas as pd
import matplotlib.pyplot as plt

ALL_RUNS = ["A", "B", "C", "D", "E"]
summary = summarize(ALL_RUNS)
summary.to_csv(OUTPUT_DIR / "results_summary.csv", index=False)
print(summary.to_string(index=False))
print()
print(summary.to_markdown(index=False))

if len(summary):
    fig, ax = plt.subplots(figsize=(7, 4.2))
    bars = ax.bar(summary["run"], summary["accuracy_%"], color="#4878CF")
    ax.set_ylabel("Accuracy (%)"); ax.set_ylim(0, 100)
    ax.set_title(f"Accuracy by run (n={int(summary['n'].max())} held-out questions)")
    for b, v in zip(bars, summary["accuracy_%"]):
        ax.text(b.get_x() + b.get_width()/2, v + 1, f"{v:.1f}", ha="center")
    fig.tight_layout()
    for ext in ("pdf", "png"):
        fig.savefig(OUTPUT_DIR / f"accuracy_by_run.{ext}")
    plt.close(fig)

    fig, ax = plt.subplots(figsize=(7, 4.2))
    bars = ax.bar(summary["run"], summary["avg_words"], color="#EE854A")
    ax.set_ylabel("Avg response length (words)")
    ax.set_title("Average response length by run")
    for b, v in zip(bars, summary["avg_words"]):
        ax.text(b.get_x() + b.get_width()/2, v + 5, f"{v:.0f}", ha="center")
    fig.tight_layout()
    for ext in ("pdf", "png"):
        fig.savefig(OUTPUT_DIR / f"words_by_run.{ext}")
    plt.close(fig)

    fig, ax = plt.subplots(figsize=(7, 4.2))
    w = 0.35
    x = range(len(summary))
    ax.bar([i - w/2 for i in x], summary["mcq_acc_%"], w, label="MCQ", color="#4878CF")
    ax.bar([i + w/2 for i in x], summary["free_acc_%"], w, label="Free-form", color="#6ACC64")
    ax.set_xticks(list(x)); ax.set_xticklabels(summary["run"])
    ax.set_ylabel("Accuracy (%)"); ax.set_ylim(0, 100); ax.legend()
    ax.set_title("Accuracy by question type")
    fig.tight_layout()
    for ext in ("pdf", "png"):
        fig.savefig(OUTPUT_DIR / f"accuracy_by_type.{ext}")
    plt.close(fig)
    print("Saved plots to", OUTPUT_DIR)

# GRPO training reward curves (rolling mean) for the report
fig, ax = plt.subplots(figsize=(7, 4.2))
plotted = False
for name, color in [("D", "#4878CF"), ("E", "#D65F5F")]:
    log_path = OUTPUT_DIR / f"{name}_train_log.jsonl"
    if not log_path.exists():
        continue
    rows = [json.loads(l) for l in open(log_path, encoding="utf-8") if l.strip()]
    means = [sum(r["rewards"]) / len(r["rewards"]) for r in rows]
    window = max(1, min(20, len(means) // 5))
    rolling = [sum(means[max(0, i - window + 1):i + 1]) / len(means[max(0, i - window + 1):i + 1])
               for i in range(len(means))]
    ax.plot(rolling, label=f"Run {name} (window={window})", color=color)
    plotted = True
if plotted:
    ax.set_xlabel("Training step"); ax.set_ylabel("Mean rollout reward (rolling)")
    ax.set_title("GRPO training reward")
    ax.legend(); fig.tight_layout()
    for ext in ("pdf", "png"):
        fig.savefig(OUTPUT_DIR / f"grpo_training_curve.{ext}")
    print("Saved GRPO training curve.")
plt.close(fig)

# Qualitative case studies for the report: questions B fixed vs A, and B's remaining misses
def load_run(name):
    p = OUTPUT_DIR / f"run_{name}.jsonl"
    return {r["id"]: r for r in (json.loads(l) for l in open(p, encoding="utf-8"))} \
        if p.exists() else {}

ra, rb = load_run("A"), load_run("B")
fixed   = [i for i in rb if i in ra and rb[i]["correct"] and not ra[i]["correct"]]
broken  = [i for i in rb if i in ra and not rb[i]["correct"] and ra[i]["correct"]]
print(f"B fixed {len(fixed)} questions that A missed; B broke {len(broken)} that A had right.")
for i in fixed[:2]:
    print("\n--- fixed example (id", i, ") gold:", rb[i]["gold"], "pred:", rb[i]["pred"], "---")
    print(rb[i]["response"][-400:])
for i in broken[:1]:
    print("\n--- regression example (id", i, ") gold:", rb[i]["gold"], "pred:", rb[i]["pred"], "---")
    print(rb[i]["response"][-400:])