# -*- coding: utf-8 -*-
"""notebook9b91f0c9f9

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/#fileId=https%3A//storage.googleapis.com/kaggle-colab-exported-notebooks/maggysthep/notebook9b91f0c9f9.5fe2d267-2211-49b5-9ea7-54967a348801.ipynb%3FX-Goog-Algorithm%3DGOOG4-RSA-SHA256%26X-Goog-Credential%3Dgcp-kaggle-com%2540kaggle-161607.iam.gserviceaccount.com/20260601/auto/storage/goog4_request%26X-Goog-Date%3D20260601T063848Z%26X-Goog-Expires%3D259200%26X-Goog-SignedHeaders%3Dhost%26X-Goog-Signature%3D041101b15f5e1b524802ecd984f266d060cd0000aac568ab427f65fc7a356f6ae1233c16b77902109b28c51171700d6ea4c938ee43b6fb4c155ae8d8cde4047157d34668a24456ac98502f44040c011a55d5e1ac4ff5d8de58cd56be1033026eecf28d8121e5e347dc5c07a5bea2af54f618efe3eeb9b7677c7bc0d19832fd01a177b50d81bd1294456b90dcbcb59da828b17d1356656b2eb4b080336d6c0e4a857ea2e6664314de9bb1b2e65ae5c6d24a9119728da28cb7028b2f8940b5d25e004e111ecfd11b6e15d23f05438a66d27a9fe0dd00a72d0719e94b20617c2469623384322e0f9b6fbb1f4deb58e168cb0e0a143fb42f15592e489a9e07c410f4
"""

# IMPORTANT: SOME KAGGLE DATA SOURCES ARE PRIVATE
# RUN THIS CELL IN ORDER TO IMPORT YOUR KAGGLE DATA SOURCES.
import kagglehub
kagglehub.login()

# IMPORTANT: RUN THIS CELL IN ORDER TO IMPORT YOUR KAGGLE DATA SOURCES,
# THEN FEEL FREE TO DELETE THIS CELL.
# NOTE: THIS NOTEBOOK ENVIRONMENT DIFFERS FROM KAGGLE'S PYTHON
# ENVIRONMENT SO THERE MAY BE MISSING LIBRARIES USED BY YOUR
# NOTEBOOK.

maggysthep_important3_path = kagglehub.dataset_download('maggysthep/important3')
maggysthep_hahaha_path = kagglehub.dataset_download('maggysthep/hahaha')

print('Data source import complete.')

"""# CSE 151B Competition — Starter Notebook

Welcome to the **CSE 151B Spring 2026 Math Reasoning Competition**!  
This notebook walks you through the full pipeline end-to-end:

1. Setting up the Python environment with `uv`
2. Loading the competition dataset
3. Running inference with **Qwen3-4B-Thinking** via vLLM (INT8 quantized)
4. Scoring responses against ground-truth answers
5. Saving results to JSONL for submission

The public dataset (`public.jsonl`) contains questions **with** answers so you can measure accuracy locally.  
The private test set used for the leaderboard does **not** include answers — for that, skip evaluation and submit the raw responses.

## 1. Environment Setup

We use [`uv`](https://github.com/astral-sh/uv) for fast, reproducible package management.

The steps below:
1. Install `uv` into `~/.local/bin`
2. Create a virtual environment at `.venv/`
3. Install all required packages (This might take a while)

> **After running this cell, restart the kernel** so that the newly installed packages (especially `vllm` and `transformers`) are picked up by the current Python session.

### Comment Out the cell below after first installation.
"""

'''# Install uv
!wget -qO- https://astral.sh/uv/install.sh | sh

# Create a virtual environment
!uv venv .venv --seed

# Install dependencies — this is fast thanks to uv's parallel resolver
!.venv/bin/python -m pip install sympy numpy transformers vllm tqdm bitsandbytes antlr4-python3-runtime==4.11.1 ipykernel jupyter

# Install Jupyter Kernel
!.venv/bin/python -m ipykernel install --user --name cse151b --display-name "Python (cse151b)"

print("Done. Restart the kernel before proceeding.")
print("Selection process: on top right, click on current kernel '(ususally named python)' -> 'select another kernel' -> 'Jupyter Kernel' -> 'Python (cse151b)'.")'''

# 1. Install uv
!curl -LsSf https://astral.sh/uv/install.sh | sh
import os
os.environ['PATH'] = f"{os.environ['HOME']}/.cargo/bin:{os.environ['PATH']}"

# 2. Use --extra-index-url instead of --index-url
# This allows uv to look in BOTH the standard registry and the Torch registry
!uv pip install --system -U \
    wrapt \
    bitsandbytes>=0.46.1 \
    transformers \
    accelerate \
    vllm \
    sympy \
    numpy \
    antlr4-python3-runtime==4.11.1 \
    torch==2.5.1 \
    torchvision==0.20.1 \
    --extra-index-url https://download.pytorch.org/whl/cu124

"""### Run the cell below every time to activate the installed environment."""

# activate venv after installation. This needs to be run everytime.
!source ./.venv/bin/activate

!python --version

"""## 2. Imports & Configuration

All key settings are collected in one place.  
- `DATA_PATH` — public dataset with ground-truth answers (use this to measure accuracy)
- `OUTPUT_PATH` — where per-question results will be written
- `GPU_ID` — which GPU to use (update if your machine has a different device index)
- `MAX_TOKENS` — maximum tokens the model may generate per response
"""

import json
import os

# ── Configuration ─────────────────────────────────────────────────────────────
MODEL_ID    = "Qwen/Qwen3-4B-Thinking-2507"
GPU_ID      = "1"                    # CUDA_VISIBLE_DEVICES
DATA_PATH   = "/kaggle/input/datasets/maggythep/important3/private.jsonl"
OUTPUT_PATH = "results/starter_results.jsonl"
MAX_TOKENS  = 32768

os.environ["CUDA_VISIBLE_DEVICES"] = GPU_ID
os.environ["HF_TOKEN"] = "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"
from huggingface_hub import whoami
print(whoami())

import re
import sys
from pathlib import Path
from typing import Optional

from transformers import AutoTokenizer
from vllm import LLM, SamplingParams
from tqdm import tqdm

"""## 3. Load the Dataset

The dataset is stored as newline-delimited JSON (`.jsonl`). Each line is one question with the following fields:

| Field | Description |
|---|---|
| `id` | Unique question identifier |
| `question` | Problem statement |
| `options` | List of answer choices — present for **MCQ**, absent for **free-form** |
| `answer` | Ground-truth answer (letter for MCQ, value/list for free-form) |
"""

DATA_PATH = "/kaggle/input/datasets/maggysthep/important3/aaaa/private.jsonl"
with open(DATA_PATH, 'r') as f:
    data = [json.loads(line) for line in f]
n_mcq  = sum(bool(d.get("options")) for d in data)
n_free = sum(not d.get("options")   for d in data)
print(f"Loaded {len(data)} questions  ({n_mcq} MCQ, {n_free} free-form)")

# Preview one MCQ and one free-form item
mcq_sample  = next(d for d in data if d.get("options"))
free_sample = next(d for d in data if not d.get("options"))

print("\n── MCQ sample ──")
print(json.dumps(mcq_sample, indent=2))
print("\n── Free-form sample ──")
print(json.dumps(free_sample, indent=2))

"""## 4. Prompt Construction

We use two system prompts depending on the question type:

- **MCQ** — the model must select the best answer letter and wrap it in `\boxed{}`
- **Free-form** — the model solves step-by-step and puts the final answer in `\boxed{}`

`build_prompt()` returns the appropriate `(system, user)` pair for each item.
"""

'''SYSTEM_PROMPT_MATH = (
    "You are an expert mathematician. Solve the problem step-by-step. "
    "Put your final answer inside \\boxed{}. "
    "If the problem has multiple sub-answers, separate them by commas inside a single \\boxed{}, "
    "e.g. \\boxed{3, 7}."
)

SYSTEM_PROMPT_MCQ = (
    "You are an expert mathematician. "
    "Read the problem and the answer choices below, then select the single best answer. "
    "Output ONLY the letter of your chosen option inside \\boxed{}, e.g. \\boxed{C}."
)


def build_prompt(question: str, options: Optional[list]) -> tuple[str, str]:
    """Return (system_prompt, user_prompt) for a question."""
    if options:
        labels    = [chr(65 + i) for i in range(len(options))]
        opts_text = "\n".join(f"{lbl}. {opt.strip()}" for lbl, opt in zip(labels, options))
        return SYSTEM_PROMPT_MCQ, f"{question}\n\nOptions:\n{opts_text}"
    return SYSTEM_PROMPT_MATH, question


# Verify with samples
for label, item in [("MCQ", mcq_sample), ("Free-form", free_sample)]:
    sys_p, usr_p = build_prompt(item["question"], item.get("options"))
    print(f"── {label} user prompt (first 200 chars) ──")
    print(usr_p[:200], "...\n")'''

from typing import Optional
import re
SYSTEM_PROMPT_MATH = (
    r"You are an expert mathematician. Solve the problem step-by-step, but keep it ultra-concise. "
    r"Ensure your final answer appears quickly and is formatted exactly as \boxed{your_answer}. "
    r"If the problem has multiple sub-answers, separate them by commas inside a single \boxed{}, e.g. \boxed{3, 7}."
    "\n\nexample:\n"
    r"question: Evaluate $\int_{-\infty}^{\infty} \frac{b^2}{x^2 + 4b^2} dx$" + "\n"
    r"reasoning: Factor out $b^2$ and use the antiderivative $\frac{1}{2b}\arctan(\frac{x}{2b})$. "
    r"Evaluating from $-\infty$ to $\infty$ yields $b^2 \cdot \frac{1}{2b} \cdot (\frac{\pi}{2} - (-\frac{\pi}{2}))$, "
    r"which simplifies to $\frac{\pi b}{2}$." + "\n"
    r"\boxed{\frac{\pi b}{2}}"
)

SYSTEM_PROMPT_MCQ = (
    "You are an expert mathematician. "
    "Read the problem and the answer choices below, then select the single best answer. "
    r"Output ONLY the letter of your chosen option inside \boxed{}, e.g. \boxed{C}."
    "\nYou do not need to include any explanation or additional text.\n"
    "\nexample:\n"
    "Question: What is 10th fibonacci term?\n"
    "options:\nA. 55\nB. 34\nC. 21\n"
    r"\boxed{A}"
)


def build_prompt(question: str, options: Optional[list]) -> tuple[str, str]:
    """Return (system_prompt, user_prompt) for a question."""
    if options:
        labels    = [chr(65 + i) for i in range(len(options))]
        opts_text = "\n".join(f"{lbl}. {opt.strip()}" for lbl, opt in zip(labels, options))
        return SYSTEM_PROMPT_MCQ, f"{question}\n\nOptions:\n{opts_text}"
    return SYSTEM_PROMPT_MATH, question

mcq_sample = {"question": "What is 2+2?", "options": ["3", "4", "5"]}
free_sample = {"question": "Solve x + 5 = 10"}

# Verify with samples
for label, item in [("MCQ", mcq_sample), ("Free-form", free_sample)]:
    sys_p, usr_p = build_prompt(item["question"], item.get("options"))
    print(f"── {label} System Prompt ──")
    print(sys_p)
    print(f"── {label} User Prompt ──")
    print(usr_p, "\n")

'''USE_MAJORITY_VOTING = False  # Set to True to enable voting (slower but potentially more accurate)
NUM_VOTES = 3               # Number of generations per question for voting
def extract_boxed_answer(response: str) -> str:
    """Extract the content inside \boxed{}."""
    import re
    match = re.search(r'\\boxed\{([^}]+)\}', response)
    return match.group(1).strip() if match else ""
def majority_vote(responses: list[str]) -> str:
    """Return the most common boxed answer from multiple responses."""
    from collections import Counter
    answers = [extract_boxed_answer(r) for r in responses if extract_boxed_answer(r)]
    if not answers:
        return responses[0] if responses else ""
    return Counter(answers).most_common(1)[0][0]
    '''

"""## 5. Load Model with vLLM (for general case, vLLM is faster)

We load **Qwen3-4B-Thinking-2507** with **INT8 quantization** via BitsAndBytes.  
Setting `load_format="bitsandbytes"` tells vLLM to apply on-the-fly INT8 weight quantization, roughly halving GPU memory usage compared to BF16.

Key parameters:
- `gpu_memory_utilization` — fraction of GPU VRAM reserved for the model and KV cache
- `max_model_len` — maximum sequence length (prompt + generation)
- `max_num_seqs` — maximum number of sequences processed in parallel
"""

'''!uv pip install --python .venv/bin/python --force-reinstall "transformers==4.48.3"'''

'''from transformers import AutoTokenizer
tokenizer = AutoTokenizer.from_pretrained(MODEL_ID)
tokenizer.pad_token = tokenizer.eos_token

llm = LLM(
model=MODEL_ID,
     quantization="bitsandbytes",
     load_format="bitsandbytes",
     enable_prefix_caching=False,
     gpu_memory_utilization=0.50,
     max_model_len=16384,
     trust_remote_code=True,
     max_num_seqs=256,
     max_num_batched_tokens=32768,
 )

sampling_params = SamplingParams(
     max_tokens=8192,
     temperature=0.6,
     top_p=0.95,
     top_k=20,
     min_p=0.0,
     presence_penalty=0.0,
     repetition_penalty=1.0,
 )

print("Model loaded.")'''

"""## 5. Load Model with Transformers (alternative to vLLM for DataHub)

We load **Qwen3-4B-Thinking-2507** with **INT4 quantization** via BitsAndBytes.  

Key parameters:
- `load_in_4bit` — quantization strategy of INT4
"""

'''!.venv/bin/python -m pip install -U bitsandbytes>=0.46.1'''

import torch
from transformers import AutoTokenizer, AutoModelForCausalLM, BitsAndBytesConfig

MODEL_ID = "Qwen/Qwen3-4B-Thinking-2507"

tokenizer = AutoTokenizer.from_pretrained(MODEL_ID, trust_remote_code=True)
#tokenizer.padding_side='left'
tokenizer.pad_token = tokenizer.eos_token

bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_compute_dtype=torch.bfloat16,
    bnb_4bit_use_double_quant=True,
)

llm = AutoModelForCausalLM.from_pretrained(
    MODEL_ID,
    trust_remote_code=True,
    quantization_config=bnb_config,
    device_map="auto",
)

"""## 6. Generate Responses

We format every question into a chat-template prompt, then call `llm.generate()` in one batched pass.  
vLLM handles batching and scheduling internally — no manual batching needed.
"""

fos.

"""### Generate with vLLM"""

''' # Build prompts for first 5 entries
prompts = []
 for item in data[:5]:
    system, user = build_prompt(item["question"], item.get("options"))
     prompt_text = tokenizer.apply_chat_template(
         [{"role": "system", "content": system},
          {"role": "user",   "content": user}],
         tokenize=False,
         add_generation_prompt=True,
     )
    prompts.append(prompt_text)

 # Generate
 print(f"Generating responses for {len(prompts)} questions...")
 outputs = llm.generate(prompts, sampling_params=sampling_params)

 responses = [out.outputs[0].text.strip() for out in outputs]

 # Preview first 3
 for i in range(min(3, len(responses))):
     print(f"\n── Response {i} (id={data[i].get('id')}) ──")
     print(responses[i][:400], "..." if len(responses[i]) > 400 else "")'''

"""### Generate with Transformers (for Datahub)"""

'''# Build prompts for ALL entries (or first N for testing)
from transformers import TextStreamer

N_TO_PROCESS = 5  # Set to smaller number for quick testing, e.g., 10
prompts = []
question_types = []  # Track if MCQ or free-form for sampling
for item in data[:N_TO_PROCESS]:
    system, user = build_prompt(item["question"], item.get("options"))
    prompt_text = tokenizer.apply_chat_template(
        [{"role": "system", "content": system},
         {"role": "user",   "content": user}],
        tokenize=False,
        add_generation_prompt=True,
    )
    prompts.append(prompt_text)
    question_types.append(bool(item.get("options")))  # True for MCQ

# Generate responses
print(f"Generating responses for {len(prompts)} questions...")
responses = []

for i, (prompt, is_mcq) in enumerate(zip(prompts, question_types)):
    if USE_MAJORITY_VOTING:
        # Generate multiple responses for voting
        candidate_responses = []
        for _ in range(NUM_VOTES):
            inputs = tokenizer(
                [prompt],
                return_tensors="pt",
                padding=True,
                truncation=True,
                max_length=2048,
            ).to(llm.device)
            streamer = TextStreamer(
                tokenizer,
                skip_prompt=True,
                skip_special_tokens=True,
            )
            with torch.no_grad():
                output_ids = llm.generate(
                    **inputs,
                    max_new_tokens=2048,
                    temperature=0.1,
                    top_p=0.1,
                    top_k=20,
                    repetition_penalty=1.0,
                    do_sample=True,
                    streamer=streamer,

                )

            new_tokens = output_ids[0][inputs["input_ids"].shape[1]:]
            response = tokenizer.decode(new_tokens, skip_special_tokens=True).strip()
            candidate_responses.append(response)

        # Majority vote on boxed answers
        final_response = majority_vote(candidate_responses)
    else:
        # Single generation
        inputs = tokenizer(
            [prompt],
            return_tensors="pt",
            padding=True,
            truncation=True,
            max_length=16384,
        ).to(llm.device)
        streamer = TextStreamer(
            tokenizer,
            skip_prompt=True,
            skip_special_tokens=True,
        )
        with torch.no_grad():
            output_ids = llm.generate(
                **inputs,
                max_new_tokens=2048,
                temperature=0.1,
                top_p=0.1,
                top_k=20,
                repetition_penalty=1.0,
                do_sample=True,
                streamer=streamer,
            )

        new_tokens = output_ids[0][inputs["input_ids"].shape[1]:]
        final_response = tokenizer.decode(new_tokens, skip_special_tokens=True).strip()

    responses.append(final_response)

# Preview first 3
for i in range(min(3, len(responses))):
    print(f"\n── Response {i} (id={data[i].get('id')}) ──")
    print(responses[i][:400], "..." if len(responses[i]) > 400 else "")'''

import gc
import re
import torch
from transformers import StoppingCriteria

# Criteria to stop Step 1 once the thinking process hits roughly 100 words
class WordCountStoppingCriteria(StoppingCriteria):
    def __init__(self, prompt_length, max_words=100):
        self.prompt_length = prompt_length
        self.max_words = max_words

    def __call__(self, input_ids, scores, **kwargs):
        # Extract only tokens generated during this step
        new_tokens = input_ids[0][self.prompt_length:]

        # Approximate word count by splitting on space-like token patterns
        # (or just estimate 1 word ≈ 1.3 tokens for math models)
        if len(new_tokens) >= (self.max_words * 1.3):
            return True
        return False

# Criteria to stop Step 2 when the final bracket is closed
class ClosingBracketStoppingCriteria(StoppingCriteria):
    def __init__(self, prompt_length):
        self.prompt_length = prompt_length
        self.regex = re.compile(r"\}")

    def __call__(self, input_ids, scores, **kwargs):
        new_tokens = input_ids[0][self.prompt_length:]
        text = tokenizer.decode(new_tokens, skip_special_tokens=True)
        return bool(self.regex.search(text))


responses = []
for i, item in enumerate(data):
#for i, item in enumerate(data[413:], start=413):
    system, user = build_prompt(item["question"], item.get("options"))
    prompt_text = tokenizer.apply_chat_template(
        [
            {"role": "system", "content": system},
            {"role": "user", "content": user},
        ],
        tokenize=False,
        add_generation_prompt=True,
    )

    inputs = tokenizer(prompt_text, return_tensors="pt").to(llm.device)
    initial_prompt_length = inputs["input_ids"].shape[1]

    # ── STEP 1: GENERATE ~100 WORDS OF THINKING ──
    stop_thinking = WordCountStoppingCriteria(prompt_length=initial_prompt_length, max_words=100)

    with torch.no_grad():
        thinking_outputs = llm.generate(
            **inputs,
            max_new_tokens=150, # Slightly more than 100 words max cap
            temperature=0.6,    # Allow normal thinking formatting
            do_sample=True,     # Better for chain of thought
            pad_token_id=tokenizer.eos_token_id,
            stopping_criteria=[stop_thinking],
        )

    # Decode what it thought so far
    thinking_text = tokenizer.decode(thinking_outputs[0][initial_prompt_length:], skip_special_tokens=True)

    # ── STEP 2: INJECT FORCE CLOSURE AND PRE-FILL THE BOX ──
    # Append its thoughts, a force prompt, and the start of the box
    forced_prompt = prompt_text + thinking_text + "\nTherefore, the final answer is: \\boxed{"

    step2_inputs = tokenizer(forced_prompt, return_tensors="pt").to(llm.device)
    step2_prompt_length = step2_inputs["input_ids"].shape[1]

    stop_answer = ClosingBracketStoppingCriteria(prompt_length=step2_prompt_length)

    with torch.no_grad():
        final_outputs = llm.generate(
            **step2_inputs,
            max_new_tokens=30,  # Just enough for the answer inside the box
            temperature=0.0,    # Greedy decoding for the final answer accuracy
            do_sample=False,
            pad_token_id=tokenizer.eos_token_id,
            stopping_criteria=[stop_answer],
        )

    # Extract just the answer string
    answer_tokens = final_outputs[0][step2_prompt_length:]
    raw_answer = tokenizer.decode(answer_tokens, skip_special_tokens=True).strip()

    clean_answer = raw_answer.split("}")[0]
    final_response = f"\\boxed{{{clean_answer}}}"

    # Optional: If you want to log or save what it thought during those 100 words:
    # print(f"Thoughts: {thinking_text}")

    responses.append(final_response)
    print(f"\n── Finished Response {i} (id={item.get('id')}) ──")
    print(final_response)

    # Clean up GPU
    del inputs, step2_inputs, thinking_outputs, final_outputs
    if torch.cuda.is_available():
        torch.cuda.empty_cache()
    gc.collect()

"""## 7. Score Responses

Scoring differs by question type:

- **MCQ**: extract the predicted letter from `\boxed{}` and compare to the gold letter (exact match).
- **Free-form**: use `Judger.auto_judge()` which handles symbolic and numeric equivalence.

Each result record contains `{id, is_mcq, gold, response, correct}`.
"""

import sys
import os

# 1. Point to the DIRECTORY containing the files, not the file itself
module_dir = '/kaggle/input/datasets/maggysthep/hahaha' #in .py  it would be '/kaggle/input/datasets/maggysthep/important3'

if module_dir not in sys.path:
    sys.path.append(module_dir)

# 2. Now import judger.
# Because the directory is in sys.path, it will also find 'utils' automatically.
import judger

def extract_letter(text: str) -> str:
    m = re.search(r"\\boxed\{([A-Za-z])\}", text)
    if m:
        return m.group(1).upper()
    matches = re.findall(r"\b([A-Z])\b", text.upper())
    return matches[-1] if matches else ""


def score_mcq(response: str, gold_letter: str) -> bool:
    return extract_letter(response) == gold_letter.strip().upper()


# Load Judger for free-form scoring
sys.path.insert(0, ".")
from judger import Judger
judger = Judger(strict_extract=False)

results = []
for item, response in tqdm(zip(data[:943], responses), total=len(responses), desc="Scoring"):
#for item, response in tqdm(zip(data, responses), total=len(data), desc="Scoring"):
    is_mcq = bool(item.get("options"))
    gold   = item["answer"]

    if is_mcq:
        correct = score_mcq(response, str(gold))
    else:
        gold_list = gold if isinstance(gold, list) else [gold]
        try:
            correct = judger.auto_judge(
                pred=response,
                gold=gold_list,
                options=[[]] * len(gold_list),
            )
        except Exception:
            correct = False

    results.append({
        "id":       item.get("id"),
        "is_mcq":   is_mcq,
        "gold":     gold,
        "response": response,
        "correct":  correct,
    })

print(f"Scoring complete. {len(results)} results.")

"""## 8. Summary

Print accuracy broken down by question type.
"""

mcq_res  = [r for r in results if r["is_mcq"]]
free_res = [r for r in results if not r["is_mcq"]]

def acc(subset):
    return sum(r["correct"] for r in subset) / len(subset) * 100 if subset else 0.0

print("=" * 50)
print("EVALUATION RESULTS")
print("=" * 50)
print(f"  MCQ        : {sum(r['correct'] for r in mcq_res):4d} / {len(mcq_res):4d}  ({acc(mcq_res):.2f}%)")
print(f"  Free-form  : {sum(r['correct'] for r in free_res):4d} / {len(free_res):4d}  ({acc(free_res):.2f}%)")
print(f"  Overall    : {sum(r['correct'] for r in results):4d} / {len(results):4d}  ({acc(results):.2f}%)")
print("=" * 50)

"""## 9. Save Results

Results are written as newline-delimited JSON.

**With evaluation** (public set — you have ground-truth):  
Each line: `{id, is_mcq, gold, response, correct}`

**Without evaluation** (private test set — no ground-truth available):  
Each line: `{id, is_mcq, response}` — omit `gold` and `correct`.

Toggle `SAVE_EVAL` below accordingly.
"""

SAVE_EVAL = False   # Set to False when running on the private test set

from pathlib import Path
import json

# FORCE the output to the Kaggle writable directory
OUTPUT_PATH = "/kaggle/working/results/starter_results_grpo.jsonl"

out_path = Path(OUTPUT_PATH)
# This creates /kaggle/working/results/
out_path.parent.mkdir(parents=True, exist_ok=True)

with open(out_path, "w") as f:
    for r in results:
        if SAVE_EVAL:
            record = {"id": r["id"], "is_mcq": r["is_mcq"], "gold": r["gold"],
                      "response": r["response"], "correct": r["correct"]}
        else:
            record = {"id": r["id"], "is_mcq": r["is_mcq"], "response": r["response"]}
        f.write(json.dumps(record) + "\n")

print(f"Saved {len(results)} records to {out_path}")
#welp im the only one coding and my computer keeps dying and fucking killing me so yeah i guess this is all i can do.

"""## Next Steps

This notebook gives you a working baseline. Here are directions to improve your score:

- **Prompt engineering** — try different system prompts or few-shot examples inside the user turn
- **Sampling parameters** — adjust `temperature`, `top_p`, or use majority voting across multiple samples
- **Fine-tuning** — the competition allows model fine-tuning; see the course resources for guidance

Good luck!
"""

##
import csv
import re

# 1. Paste your raw terminal printout inside this triple-quoted string
raw_log_data = """
── Finished Response 0 (id=0) ──
\boxed{13}

── Finished Response 1 (id=1) ──
\boxed{C}

── Finished Response 2 (id=2) ──
\boxed{2.07, 1.645, B}

── Finished Response 3 (id=3) ──
\boxed{B}

── Finished Response 4 (id=4) ──
\boxed{-\dfrac{7}

── Finished Response 5 (id=5) ──
\boxed{10.00}

── Finished Response 6 (id=6) ──
\boxed{142.32}

── Finished Response 7 (id=7) ──
\boxed{15}

── Finished Response 8 (id=8) ──
\boxed{378}

── Finished Response 9 (id=9) ──
\boxed{y = \frac{L - 8x}

── Finished Response 10 (id=10) ──
\boxed{A}

── Finished Response 11 (id=11) ──
\boxed{0.51}

── Finished Response 12 (id=12) ──
\boxed{2c + 4p = 70}

── Finished Response 13 (id=13) ──
\boxed{B}

── Finished Response 14 (id=14) ──
\boxed{3}

── Finished Response 15 (id=15) ──
\boxed{8}

── Finished Response 16 (id=16) ──
\boxed{500}

── Finished Response 17 (id=17) ──
\boxed{C}

── Finished Response 18 (id=18) ──
\boxed{I}

── Finished Response 19 (id=19) ──
\boxed{D}

── Finished Response 20 (id=20) ──
\boxed{210.5}

── Finished Response 21 (id=21) ──
\boxed{L(t) = 0.35t + 57.5}

── Finished Response 22 (id=22) ──
\boxed{D}

── Finished Response 23 (id=23) ──
\boxed{A}

── Finished Response 24 (id=24) ──
\boxed{0}

── Finished Response 25 (id=25) ──
\boxed{0.16, 0.12, 0.22, 0.34, 0.26,}

── Finished Response 26 (id=26) ──
\boxed{J}

── Finished Response 27 (id=27) ──
\boxed{1/3, 5/3}

── Finished Response 28 (id=28) ──
\boxed{1120 \times \frac{1}

── Finished Response 29 (id=29) ──
\boxed{34.3}

── Finished Response 30 (id=30) ──
\boxed{1065}

── Finished Response 31 (id=31) ──
\boxed{-3 }

── Finished Response 32 (id=32) ──
\boxed{7}

── Finished Response 33 (id=33) ──
\boxed{D}

── Finished Response 34 (id=34) ──
\boxed{A}

── Finished Response 35 (id=35) ──
\boxed{left, \frac{1}

── Finished Response 36 (id=36) ──
\boxed{40x^{10}

── Finished Response 37 (id=37) ──
\boxed{Chucky}

── Finished Response 38 (id=38) ──
\boxed{A}

── Finished Response 39 (id=39) ──
\boxed{475}

── Finished Response 40 (id=40) ──
\boxed{D = 800 - ื่d}

── Finished Response 41 (id=41) ──
\boxed{2025}

── Finished Response 42 (id=42) ──
\boxed{No}

── Finished Response 43 (id=43) ──
\boxed{35, 7, 14}

── Finished Response 44 (id=44) ──
\boxed{True, True, True, True}

── Finished Response 45 (id=45) ──
\boxed{F}

── Finished Response 46 (id=46) ──
\boxed{1.645}

── Finished Response 47 (id=47) ──
\boxed{F}

── Finished Response 48 (id=48) ──
\boxed{A, C}

── Finished Response 49 (id=49) ──
\boxed{0.0228}

── Finished Response 50 (id=50) ──
\boxed{140A + 150B = 5930, 3A + 4B = 142}

── Finished Response 51 (id=51) ──
\boxed{17720_8}

── Finished Response 52 (id=52) ──
\boxed{231}

── Finished Response 53 (id=53) ──
\boxed{F}

── Finished Response 54 (id=54) ──
\boxed{2}

── Finished Response 55 (id=55) ──
\boxed{y = ื่ 405 \cdot \left( \frac{x}

── Finished Response 56 (id=56) ──
\boxed{D}

── Finished Response 57 (id=57) ──
\boxed{3}

── Finished Response 58 (id=58) ──
\boxed{0}

── Finished Response 59 (id=59) ──
\boxed{49}

── Finished Response 60 (id=60) ──
\boxed{C}

── Finished Response 61 (id=61) ──
\boxed{0.76c \text{ if }

── Finished Response 62 (id=62) ──
\boxed{15, 192, 0}

── Finished Response 63 (id=63) ──
\boxed{16.2, 19.8}

── Finished Response 64 (id=64) ──
\boxed{500 + 700 \cos\left(\frac{\pi}

── Finished Response 65 (id=65) ──
\boxed{-\dfrac{6}

── Finished Response 66 (id=66) ──
\boxed{1200}

── Finished Response 67 (id=67) ──
\boxed{N = 7.6 \times (1.09)^t}

── Finished Response 68 (id=68) ──
\boxed{1.2857}

── Finished Response 69 (id=69) ──
\boxed{C}

── Finished Response 70 (id=70) ──
\boxed{5/56}

── Finished Response 71 (id=71) ──
\boxed{1.2, 18}

── Finished Response 72 (id=72) ──
\boxed{0.55}

── Finished Response 73 (id=73) ──
\boxed{E}

── Finished Response 74 (id=74) ──
\boxed{(-0.5, 1.5)}

── Finished Response 75 (id=75) ──
\boxed{1100 + 0.11x < 1450 + 0.15(x - 8000}

── Finished Response 76 (id=76) ──
\boxed{11}

── Finished Response 77 (id=77) ──
\boxed{D}

── Finished Response 78 (id=78) ──
\boxed{B}

── Finished Response 79 (id=79) ──
\boxed{25/7}

── Finished Response 80 (id=80) ──
\boxed{F}

── Finished Response 81 (id=81) ──
\boxed{76}

── Finished Response 82 (id=82) ──
\boxed{1.23}

── Finished Response 83 (id=83) ──
\boxed{100}

── Finished Response 84 (id=84) ──
\boxed{4-8=-4}

── Finished Response 85 (id=85) ──
\boxed{H}

── Finished Response 86 (id=86) ──
\boxed{15}

── Finished Response 87 (id=87) ──
\boxed{OBSERVATION}

── Finished Response 88 (id=88) ──
\boxed{C}

── Finished Response 89 (id=89) ──
\boxed{30}

── Finished Response 90 (id=90) ──
\boxed{8 + 7(n - 1)}

── Finished Response 91 (id=91) ──
\boxed{A}

── Finished Response 92 (id=92) ──
\boxed{C}

── Finished Response 93 (id=93) ──
\boxed{1}

── Finished Response 94 (id=94) ──
\boxed{D}

── Finished Response 95 (id=95) ──
\boxed{7}

── Finished Response 96 (id=96) ──
\boxed{52}

── Finished Response 97 (id=97) ──
\boxed{0}

── Finished Response 98 (id=98) ──
\boxed{E}

── Finished Response 99 (id=99) ──
\boxed{6}

── Finished Response 100 (id=100) ──
\boxed{135}

── Finished Response 101 (id=101) ──
\boxed{C, C, A, B}

── Finished Response 102 (id=102) ──
\boxed{C}

── Finished Response 103 (id=103) ──
\boxed{16 \times \sin(45^\circ)}

── Finished Response 104 (id=104) ──
\boxed{7.7 \times \frac{31\pi}

── Finished Response 105 (id=105) ──
\boxed{24}

── Finished Response 106 (id=106) ──
\boxed{2.5}

── Finished Response 107 (id=107) ──
\boxed{D}

── Finished Response 108 (id=108) ──
\boxed{72}

── Finished Response 109 (id=109) ──
\boxed{A}

── Finished Response 110 (id=110) ──
\boxed{A}

── Finished Response 111 (id=111) ──
\boxed{32x^{3}

── Finished Response 112 (id=112) ──
\boxed{100}

── Finished Response 113 (id=113) ──
\boxed{\frac{20 - x^2}

── Finished Response 114 (id=114) ──
\boxed{J}

── Finished Response 115 (id=115) ──
\boxed{y = 12.5x + 13408 - 12.5*1328}

── Finished Response 116 (id=116) ──
\boxed{24, 12}

── Finished Response 117 (id=117) ──
\boxed{B}

── Finished Response 118 (id=118) ──
\boxed{3.6}

── Finished Response 119 (id=119) ──
\boxed{C, A, D, B}

── Finished Response 120 (id=120) ──
\boxed{100}

── Finished Response 121 (id=121) ──
\boxed{35}

── Finished Response 122 (id=122) ──
\boxed{1174.8}

── Finished Response 123 (id=123) ──
\boxed{C}

── Finished Response 124 (id=124) ──
\boxed{H}

── Finished Response 125 (id=125) ──
\boxed{12}

── Finished Response 126 (id=126) ──
\boxed{137939.09...}

── Finished Response 127 (id=127) ──
\boxed{5}

── Finished Response 128 (id=128) ──
\boxed{1}

── Finished Response 129 (id=129) ──
\boxed{5}

── Finished Response 130 (id=130) ──
\boxed{r^{42}

── Finished Response 131 (id=131) ──
\boxed{0.0001}

── Finished Response 132 (id=132) ──
\boxed{32}

── Finished Response 133 (id=133) ──
\boxed{-\frac{\sqrt{3}

── Finished Response 134 (id=134) ──
\boxed{28.5}

── Finished Response 135 (id=135) ──
\boxed{3/5}

── Finished Response 136 (id=136) ──
\boxed{A}

── Finished Response 137 (id=137) ──
\boxed{2/13}

── Finished Response 138 (id=138) ──
\boxed{0.1641 \times (210)^2}

── Finished Response 139 (id=139) ──
\boxed{201, \frac{1}

── Finished Response 140 (id=140) ──
\boxed{49 \times (45 + 11)}

── Finished Response 141 (id=141) ──
\boxed{G}

── Finished Response 142 (id=142) ──
\boxed{7,8,9,10,11}

── Finished Response 143 (id=143) ──
\boxed{0, -8}

── Finished Response 144 (id=144) ──
\boxed{B}

── Finished Response 145 (id=145) ──
\boxed{M(x) = \frac{x}

── Finished Response 146 (id=146) ──
\boxed{E}

── Finished Response 147 (id=147) ──
\boxed{J}

── Finished Response 148 (id=148) ──
\boxed{I}

── Finished Response 149 (id=149) ──
\boxed{123.45}

── Finished Response 150 (id=150) ──
\boxed{C}

── Finished Response 151 (id=151) ──
\boxed{6}

── Finished Response 152 (id=152) ──
\boxed{A}

── Finished Response 153 (id=153) ──
\boxed{C}

── Finished Response 154 (id=154) ──
\boxed{12.75}

── Finished Response 155 (id=155) ──
\boxed{14.00}

── Finished Response 156 (id=156) ──
\boxed{B}

── Finished Response 157 (id=157) ──
\boxed{7\cos(0.1t) - 5\sin(0.1t) + 7}

── Finished Response 158 (id=158) ──
\boxed{A}

── Finished Response 159 (id=159) ──
\boxed{0.07}

── Finished Response 160 (id=160) ──
\boxed{1, \text{multiplicative identity}

── Finished Response 161 (id=161) ──
\boxed{a_{2025}

── Finished Response 162 (id=162) ──
\boxed{C}

── Finished Response 163 (id=163) ──
\boxed{1, -9, 0}

── Finished Response 164 (id=164) ──
\boxed{J}

── Finished Response 165 (id=165) ──
\boxed{B}

── Finished Response 166 (id=166) ──
\boxed{175 \left( \frac{ื่}

── Finished Response 167 (id=167) ──
\boxed{B, A, B, A}

── Finished Response 168 (id=168) ──
\boxed{A}

── Finished Response 169 (id=169) ──
\boxed{375}

── Finished Response 170 (id=170) ──
\boxed{B}

── Finished Response 171 (id=171) ──
\boxed{20}

── Finished Response 172 (id=172) ──
\boxed{22/61}

── Finished Response 173 (id=173) ──
\boxed{F}

── Finished Response 174 (id=174) ──
\boxed{7}

── Finished Response 175 (id=175) ──
\boxed{A}

── Finished Response 176 (id=176) ──
\boxed{w = \frac{ื่}

── Finished Response 177 (id=177) ──
\boxed{C}

── Finished Response 178 (id=178) ──
\boxed{C}

── Finished Response 179 (id=179) ──
\boxed{29, 3}

── Finished Response 180 (id=180) ──
\boxed{-\frac{7}

── Finished Response 181 (id=181) ──
\boxed{A}

── Finished Response 182 (id=182) ──
\boxed{E}

── Finished Response 183 (id=183) ──
\boxed{B}

── Finished Response 184 (id=184) ──
\boxed{J}

── Finished Response 185 (id=185) ──
\boxed{True, True, True, True, False}

── Finished Response 186 (id=186) ──
\boxed{D}

── Finished Response 187 (id=187) ──
\boxed{0.002}

── Finished Response 188 (id=188) ──
\boxed{60.50}

── Finished Response 189 (id=189) ──
\boxed{850a + 1200r = 35000}

── Finished Response 190 (id=190) ──
\boxed{-\dfrac{21}

── Finished Response 191 (id=191) ──
\boxed{D, A, C, B, E}

── Finished Response 192 (id=192) ──
\boxed{C}

── Finished Response 193 (id=193) ──
\boxed{B}

── Finished Response 194 (id=194) ──
\boxed{600}

── Finished Response 195 (id=195) ──
\boxed{(-0.1, 2.9)}

── Finished Response 196 (id=196) ──
\boxed{14.5854}

── Finished Response 197 (id=197) ──
\boxed{1.5}

── Finished Response 198 (id=198) ──
\boxed{3}

── Finished Response 199 (id=199) ──
\boxed{100}

── Finished Response 200 (id=200) ──
\boxed{J}

── Finished Response 201 (id=201) ──
\boxed{1(5t + 8)^2}

── Finished Response 202 (id=202) ──
\boxed{108/70}

── Finished Response 203 (id=203) ──
\boxed{A}

── Finished Response 204 (id=204) ──
\boxed{E}

── Finished Response 205 (id=205) ──
\boxed{3/4}

── Finished Response 206 (id=206) ──
\boxed{11 - 7}

── Finished Response 207 (id=207) ──
\boxed{12}

── Finished Response 208 (id=208) ──
\boxed{16.2}

── Finished Response 209 (id=209) ──
\boxed{C}

── Finished Response 210 (id=210) ──
\boxed{\frac{7}

── Finished Response 211 (id=211) ──
\boxed{G}

── Finished Response 212 (id=212) ──
\boxed{J}

── Finished Response 213 (id=213) ──
\boxed{43/72 - ื่3/8}

── Finished Response 214 (id=214) ──
\boxed{11}

── Finished Response 215 (id=215) ──
\boxed{122}

── Finished Response 216 (id=216) ──
\boxed{60}

── Finished Response 217 (id=217) ──
\boxed{D}

── Finished Response 218 (id=218) ──
\boxed{\arcsin\left( \frac{7}

── Finished Response 219 (id=219) ──
\boxed{18}

── Finished Response 220 (id=220) ──
\boxed{A}

── Finished Response 221 (id=221) ──
\boxed{2750}

── Finished Response 222 (id=222) ──
\boxed{J}

── Finished Response 223 (id=223) ──
\boxed{C}

── Finished Response 224 (id=224) ──
\boxed{193 + 25*98}

── Finished Response 225 (id=225) ──
\boxed{1.57, 5, 2.01, A}

── Finished Response 226 (id=226) ──
\boxed{2}

── Finished Response 227 (id=227) ──
\boxed{A}

── Finished Response 228 (id=228) ──
\boxed{v^7}

── Finished Response 229 (id=229) ──
\boxed{2}

── Finished Response 230 (id=230) ──
\boxed{\log_{1.6}

── Finished Response 231 (id=231) ──
\boxed{y = 1.5 + 0.5x}

── Finished Response 232 (id=232) ──
\boxed{3}

── Finished Response 233 (id=233) ──
\boxed{1.96, -1.96, 1.96, A}

── Finished Response 234 (id=234) ──
\boxed{29x^7 + 6x^ื่}

── Finished Response 235 (id=235) ──
\boxed{J}

── Finished Response 236 (id=236) ──
\boxed{6e}

── Finished Response 237 (id=237) ──
\boxed{50\%}

── Finished Response 238 (id=238) ──
\boxed{1, 1, 1}

── Finished Response 239 (id=239) ──
\boxed{35}

── Finished Response 240 (id=240) ──
\boxed{16}

── Finished Response 241 (id=241) ──
\boxed{B}

── Finished Response 242 (id=242) ──
\boxed{238.5}

── Finished Response 243 (id=243) ──
\boxed{0.8925}

── Finished Response 244 (id=244) ──
\boxed{F}

── Finished Response 245 (id=245) ──
\boxed{980}

── Finished Response 246 (id=246) ──
\boxed{25, 23, 17, 23, 23}

── Finished Response 247 (id=247) ──
\boxed{A}

── Finished Response 248 (id=248) ──
\boxed{180}

── Finished Response 249 (id=249) ──
\boxed{B}

── Finished Response 250 (id=250) ──
\boxed{0}

── Finished Response 251 (id=251) ──
\boxed{176.8}

── Finished Response 252 (id=252) ──
\boxed{C}

── Finished Response 253 (id=253) ──
\boxed{C}

── Finished Response 254 (id=254) ──
\boxed{D}

── Finished Response 255 (id=255) ──
\boxed{A}

── Finished Response 256 (id=256) ──
\boxed{30, -30}

── Finished Response 257 (id=257) ──
\boxed{2.76 \pm 1.96 \times \frac{0.51}

── Finished Response 258 (id=258) ──
\boxed{F}

── Finished Response 259 (id=259) ──
\boxed{C}

── Finished Response 260 (id=260) ──
\boxed{-22 }

── Finished Response 261 (id=261) ──
\boxed{3}

── Finished Response 262 (id=262) ──
\boxed{850 - 50t}

── Finished Response 263 (id=263) ──
\boxed{J}

── Finished Response 264 (id=264) ──
\boxed{4\pi (8t)^2}

── Finished Response 265 (id=265) ──
\boxed{A}

── Finished Response 266 (id=266) ──
\boxed{C}

── Finished Response 267 (id=267) ──
\boxed{H}

── Finished Response 268 (id=268) ──
\boxed{4950}

── Finished Response 269 (id=269) ──
\boxed{1.789}

── Finished Response 270 (id=270) ──
\boxed{12}

── Finished Response 271 (id=271) ──
\boxed{0, -2, 2}

── Finished Response 272 (id=272) ──
\boxed{B}

── Finished Response 273 (id=273) ──
\boxed{0}

── Finished Response 274 (id=274) ──
\boxed{C}

── Finished Response 275 (id=275) ──
\boxed{2026}

── Finished Response 276 (id=276) ──
\boxed{3.5}

── Finished Response 277 (id=277) ──
\boxed{38721.05}

── Finished Response 278 (id=278) ──
\boxed{38}

── Finished Response 279 (id=279) ──
\boxed{J}

── Finished Response 280 (id=280) ──
\boxed{B}

── Finished Response 281 (id=281) ──
\boxed{-.4618}

── Finished Response 282 (id=282) ──
\boxed{e^2}

── Finished Response 283 (id=283) ──
\boxed{113}

── Finished Response 284 (id=284) ──
\boxed{B}

── Finished Response 285 (id=285) ──
\boxed{0}

── Finished Response 286 (id=286) ──
\boxed{C}

── Finished Response 287 (id=287) ──
\boxed{664}

── Finished Response 288 (id=288) ──
\boxed{128 \cdot (0.9)^{n-1}

── Finished Response 289 (id=289) ──
\boxed{4, 10}

── Finished Response 290 (id=290) ──
\boxed{C}

── Finished Response 291 (id=291) ──
\boxed{1920}

── Finished Response 292 (id=292) ──
\boxed{-\sqrt{3}

── Finished Response 293 (id=293) ──
\boxed{P(t) = -4300 + 150t}

── Finished Response 294 (id=294) ──
\boxed{6}

── Finished Response 295 (id=295) ──
\boxed{C}

── Finished Response 296 (id=296) ──
\boxed{15}

── Finished Response 297 (id=297) ──
\boxed{A. 1.02, B. (1.02, \infty), C. 0.15, D.}

── Finished Response 298 (id=298) ──
\boxed{A}

── Finished Response 299 (id=299) ──
\boxed{18805.7}

── Finished Response 300 (id=300) ──
\boxed{6487.5}

── Finished Response 301 (id=301) ──
\boxed{0.972}

── Finished Response 302 (id=302) ──
\boxed{B}

── Finished Response 303 (id=303) ──
\boxed{C}

── Finished Response 304 (id=304) ──
\boxed{I}

── Finished Response 305 (id=305) ──
\boxed{B}

── Finished Response 306 (id=306) ──
\boxed{G}

── Finished Response 307 (id=307) ──
\boxed{3 - \frac{5}

── Finished Response 308 (id=308) ──
\boxed{12}

── Finished Response 309 (id=309) ──
\boxed{82939}

── Finished Response 310 (id=310) ──
\boxed{6 + 4k}

── Finished Response 311 (id=311) ──
\boxed{10^{(8.3 - 5.1)}

── Finished Response 312 (id=312) ──
\boxed{3}

── Finished Response 313 (id=313) ──
\boxed{-\sqrt{1 - (13/15)^2}

── Finished Response 314 (id=314) ──
\boxed{7, -8, -4}

── Finished Response 315 (id=315) ──
\boxed{B}

── Finished Response 316 (id=316) ──
\boxed{I}

── Finished Response 317 (id=317) ──
\boxed{H}

── Finished Response 318 (id=318) ──
\boxed{13}

── Finished Response 319 (id=319) ──
\boxed{False, True, True, False}

── Finished Response 320 (id=320) ──
\boxed{1}

── Finished Response 321 (id=321) ──
\boxed{H}

── Finished Response 322 (id=322) ──
\boxed{50, 25, 625}

── Finished Response 323 (id=323) ──
\boxed{[10, 12)}

── Finished Response 324 (id=324) ──
\boxed{D}

── Finished Response 325 (id=325) ──
\boxed{[0, 55]}

── Finished Response 326 (id=326) ──
\boxed{0.67}

── Finished Response 327 (id=327) ──
\boxed{152}

── Finished Response 328 (id=328) ──
\boxed{A: iii, B: i, C: iv, D: ii}

── Finished Response 329 (id=329) ──
\boxed{B}

── Finished Response 330 (id=330) ──
\boxed{100}

── Finished Response 331 (id=331) ──
\boxed{H}

── Finished Response 332 (id=332) ──
\boxed{386}

── Finished Response 333 (id=333) ──
\boxed{54, 62}

── Finished Response 334 (id=334) ──
\boxed{H}

── Finished Response 335 (id=335) ──
\boxed{A}

── Finished Response 336 (id=336) ──
\boxed{A}

── Finished Response 337 (id=337) ──
\boxed{B}

── Finished Response 338 (id=338) ──
\boxed{y\text{-axis symmetry}

── Finished Response 339 (id=339) ──
\boxed{C}

── Finished Response 340 (id=340) ──
\boxed{E}

── Finished Response 341 (id=341) ──
\boxed{25, 5}

── Finished Response 342 (id=342) ──
\boxed{negative}

── Finished Response 343 (id=343) ──
\boxed{1 \to D, 2 \to A, 3 \to C, 4 \to B, 5 \to E}

── Finished Response 344 (id=344) ──
\boxed{-5 }

── Finished Response 345 (id=345) ──
\boxed{-\frac{5}

── Finished Response 346 (id=346) ──
\boxed{0.7}

── Finished Response 347 (id=347) ──
\boxed{I}

── Finished Response 348 (id=348) ──
\boxed{D}

── Finished Response 349 (id=349) ──
\boxed{-\frac{1}

── Finished Response 350 (id=350) ──
\boxed{11100}

── Finished Response 351 (id=351) ──
\boxed{D}

── Finished Response 352 (id=352) ──
\boxed{68}

── Finished Response 353 (id=353) ──
\boxed{8}

── Finished Response 354 (id=354) ──
\boxed{gram, kilogram, tonne, solar mass, kilogram}

── Finished Response 355 (id=355) ──
\boxed{J}

── Finished Response 356 (id=356) ──
\boxed{C}

── Finished Response 357 (id=357) ──
\boxed{16}

── Finished Response 358 (id=358) ──
\boxed{402}

── Finished Response 359 (id=359) ──
\boxed{D}

── Finished Response 360 (id=360) ──
\boxed{C}

── Finished Response 361 (id=361) ──
\boxed{180 - 7x}

── Finished Response 362 (id=362) ──
\boxed{6x - 5y}

── Finished Response 363 (id=363) ──
\boxed{10000 \cdot (0.89)^t}

── Finished Response 364 (id=364) ──
\boxed{Y, Y, Y, N}

── Finished Response 365 (id=365) ──
\boxed{C}

── Finished Response 366 (id=366) ──
\boxed{F}

── Finished Response 367 (id=367) ──
\boxed{1.0, 1.2, 0.9}

── Finished Response 368 (id=368) ──
\boxed{C}

── Finished Response 369 (id=369) ──
\boxed{1, 5, 2}

── Finished Response 370 (id=370) ──
\boxed{y = -5}

── Finished Response 371 (id=371) ──
\boxed{0.7}

── Finished Response 372 (id=372) ──
\boxed{1.96 \times \frac{20.58}

── Finished Response 373 (id=373) ──
\boxed{50.23 < \mu < 55.87}

── Finished Response 374 (id=374) ──
\boxed{3100}

── Finished Response 375 (id=375) ──
\boxed{3.72}

── Finished Response 376 (id=376) ──
\boxed{1 + 2 + 3 + \ldots + 50}

── Finished Response 377 (id=377) ──
\boxed{B}

── Finished Response 378 (id=378) ──
\boxed{0.0000}

── Finished Response 379 (id=379) ──
\boxed{220}

── Finished Response 380 (id=380) ──
\boxed{0.075, 0ื่, 32000, 16710, 16710}

── Finished Response 381 (id=381) ──
\boxed{2040}

── Finished Response 382 (id=382) ──
\boxed{1.7w}

── Finished Response 383 (id=383) ──
\boxed{120}

── Finished Response 384 (id=384) ──
\boxed{\frac{ \ln\left( \frac{22}

── Finished Response 385 (id=385) ──
\boxed{A}

── Finished Response 386 (id=386) ──
\boxed{3}

── Finished Response 387 (id=387) ──
\boxed{480}

── Finished Response 388 (id=388) ──
\boxed{3.1, 4.1, 5.1, 7.1, 0\%}

── Finished Response 389 (id=389) ──
\boxed{I}

── Finished Response 390 (id=390) ──
\boxed{3/25}

── Finished Response 391 (id=391) ──
\boxed{E}

── Finished Response 392 (id=392) ──
\boxed{71}

── Finished Response 393 (id=393) ──
\boxed{\arccos\left( \frac{x - 6}

── Finished Response 394 (id=394) ──
\boxed{B}

── Finished Response 395 (id=395) ──
\boxed{28.333...}

── Finished Response 396 (id=396) ──
\boxed{(-\infty, 5)}

── Finished Response 397 (id=397) ──
\boxed{4\pi \cdot 64, \frac{4}

── Finished Response 398 (id=398) ──
\boxed{C}

── Finished Response 399 (id=399) ──
\boxed{B}

── Finished Response 400 (id=400) ──
\boxed{X}

── Finished Response 401 (id=401) ──
\boxed{450^\circ}

── Finished Response 402 (id=402) ──
\boxed{J}

── Finished Response 403 (id=403) ──
\boxed{J}

── Finished Response 404 (id=404) ──
\boxed{40\%}

── Finished Response 405 (id=405) ──
\boxed{D}

── Finished Response 406 (id=406) ──
\boxed{0}

── Finished Response 407 (id=407) ──
\boxed{J}

── Finished Response 408 (id=408) ──
\boxed{5816/9999}

── Finished Response 409 (id=409) ──
\boxed{(-0.5, 1.5)}

── Finished Response 410 (id=410) ──
\boxed{45}

── Finished Response 411 (id=411) ──
\boxed{8 \times \frac{196\pi}

── Finished Response 412 (id=412) ──
\boxed{...}

── Finished Response 413 (id=413) ──
\boxed{D}
"""