# -*- coding: utf-8 -*-
"""starter_code_cse151b_comp e3518d

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/#fileId=https%3A//storage.googleapis.com/kaggle-colab-exported-notebooks/maggysthep/starter-code-cse151b-comp-e3518d.09df8b56-4cc7-4794-b4e5-42c428ddc0bd.ipynb%3FX-Goog-Algorithm%3DGOOG4-RSA-SHA256%26X-Goog-Credential%3Dgcp-kaggle-com%2540kaggle-161607.iam.gserviceaccount.com/20260601/auto/storage/goog4_request%26X-Goog-Date%3D20260601T031053Z%26X-Goog-Expires%3D259200%26X-Goog-SignedHeaders%3Dhost%26X-Goog-Signature%3D6227c29828a2ff6585858eb364e8ddbd167fd4fbacc7fbf2f2ab91ac34bab44b5cdfe11ae44af6f07d46281c2be3c7d9c2cc22ba89aa1f4592e5ee738992f108d056f1f8a37aaeeef1bbd1f936603f29bafc3ded643a0acd5faa1a039c1c36eb3bafee9f1789b859d354ba875525bebdb1eafcada3adb1008a1fd9bc0042f6cda757dce7162a1da5737ae17b40add70d36958dca5f229ed3ad4eb00d174e14ef7bfc2e075085dd56a8bc87a1a0e08c327e378d65aeb7f7a51d261a49a272bcbd76f96152dc9272d4c113ffa877b236a975359d1153966dce5876d2b904e87312ded34f95112c10ff00c92d07b09a683deff6cae1d6fc62eb08cb143e88494e92
"""

# IMPORTANT: SOME KAGGLE DATA SOURCES ARE PRIVATE
# RUN THIS CELL IN ORDER TO IMPORT YOUR KAGGLE DATA SOURCES.
import kagglehub
kagglehub.login()

# IMPORTANT: RUN THIS CELL IN ORDER TO IMPORT YOUR KAGGLE DATA SOURCES,
# THEN FEEL FREE TO DELETE THIS CELL.
# NOTE: THIS NOTEBOOK ENVIRONMENT DIFFERS FROM KAGGLE'S PYTHON
# ENVIRONMENT SO THERE MAY BE MISSING LIBRARIES USED BY YOUR
# NOTEBOOK.

magnuschiu_important_path = kagglehub.dataset_download('magnuschiu/important')

print('Data source import complete.')

"""# CSE 151B Competition — Starter Notebook

Welcome to the **CSE 151B Spring 2026 Math Reasoning Competition**!  
This notebook walks you through the full pipeline end-to-end:

1. Setting up the Python environment with `uv`
2. Loading the competition dataset
3. Running inference with **Qwen3-4B-Thinking** via vLLM (INT8 quantized)
4. Scoring responses against ground-truth answers
5. Saving results to JSONL for submission

The public dataset (`public.jsonl`) contains questions **with** answers so you can measure accuracy locally.  
The private test set used for the leaderboard does **not** include answers — for that, skip evaluation and submit the raw responses.

## 1. Environment Setup

We use [`uv`](https://github.com/astral-sh/uv) for fast, reproducible package management.

The steps below:
1. Install `uv` into `~/.local/bin`
2. Create a virtual environment at `.venv/`
3. Install all required packages (This might take a while)

> **After running this cell, restart the kernel** so that the newly installed packages (especially `vllm` and `transformers`) are picked up by the current Python session.

### Comment Out the cell below after first installation.
"""

# Kaggle notebooks already provide a base Python environment.
# Install missing packages directly in this notebook session.
!pip install -q transformers vllm tqdm bitsandbytes peft accelerate sympy antlr4-python3-runtime==4.11.1

print("Dependencies installed. No virtualenv activation is needed in Kaggle.")

"""### Run the cell below every time to activate the installed environment."""

# Kaggle notebooks do not require manual virtual environment activation.
# Simply run the cells in order after installing packages.

"""## 2. Imports & Configuration

All key settings are collected in one place.  
- `DATA_PATH` — public dataset with ground-truth answers (use this to measure accuracy)
- `OUTPUT_PATH` — where per-question results will be written
- `GPU_ID` — which GPU to use (update if your machine has a different device index)
- `MAX_TOKENS` — maximum tokens the model may generate per response
"""

import json
import os
import re
import sys
from pathlib import Path
from typing import Optional
ROOT = Path('/kaggle/input/datasets/magnuschiu/important/aaaa')

# ── Configuration ─────────────────────────────────────────────────────────────
MODEL_ID    = "Qwen/Qwen3-4B-Thinking-2507"
GPU_ID      = "1"                    # CUDA_VISIBLE_DEVICES
DATA_PATH   = ROOT / "stage1" / "private.jsonl"
if not DATA_PATH.exists():
    DATA_PATH = ROOT / "private.jsonl"
if not DATA_PATH.exists():
    candidate_files = list(ROOT.glob("**/public.jsonl")) + list(ROOT.glob("**/private.jsonl"))
    DATA_PATH = candidate_files[0] if candidate_files else ROOT / "math portion" / "public.jsonl"
OUTPUT_PATH = ROOT / "results" / "starter_results.jsonl"
MAX_TOKENS  = 9182                 # lower max tokens for faster responses; increase only if needed

os.environ["CUDA_VISIBLE_DEVICES"] = GPU_ID

from transformers import AutoTokenizer
from vllm import LLM, SamplingParams
from tqdm import tqdm

"""## 3. Load the Dataset

The dataset is stored as newline-delimited JSON (`.jsonl`). Each line is one question with the following fields:

| Field | Description |
|---|---|
| `id` | Unique question identifier |
| `question` | Problem statement |
| `options` | List of answer choices — present for **MCQ**, absent for **free-form** |
| `answer` | Ground-truth answer (letter for MCQ, value/list for free-form) |
"""

import json
import pandas as pd

# ── Corrected Line-by-Line JSONL Data Loader ─────────────────────────────────
def load_data(file_path):
    parsed_data = []
    with open(file_path, 'r', encoding='utf-8') as file:
        for line_num, line in enumerate(file, 1):
            clean_line = line.strip()
            if not clean_line:
                continue  # Skip empty lines cleanly
            try:
                parsed_data.append(json.loads(clean_line))
            except json.JSONDecodeError as e:
                print(f"Skipping malformed JSON on line {line_num}: {e}")
    return parsed_data

# ── Execute Loading ──────────────────────────────────────────────────────────
data = load_data(str(DATA_PATH))

n_mcq = sum(bool(d.get("options")) for d in data)
n_free = sum(not d.get("options") for d in data)
print(f"Loaded {len(data)} questions  ({n_mcq} MCQ, {n_free} free-form)")
print(f"Using dataset: {DATA_PATH}")

# Preview one MCQ and one free-form item
mcq_sample = next((d for d in data if d.get("options")), None)
free_sample = next((d for d in data if not d.get("options")), None)

if mcq_sample:
    print("\n── MCQ sample ──")
    print(json.dumps(mcq_sample, indent=2))
else:
    print("\n── No MCQ sample found in dataset ──")

if free_sample:
    print("\n── Free-form sample ──")
    print(json.dumps(free_sample, indent=2))
else:
    print("\n── No Free-form sample found in dataset ──")

"""## 4. Prompt Construction

We use two system prompts depending on the question type:

- **MCQ** — the model must select the best answer letter and wrap it in `\boxed{}`
- **Free-form** — the model solves step-by-step and puts the final answer in `\boxed{}`

`build_prompt()` returns the appropriate `(system, user)` pair for each item.
"""

SYSTEM_PROMPT_MATH = (
    "You are an expert mathematician. Solve the problem step-by-step, showing your reasoning briefly. "
    "Put your final answer inside \\boxed{}. "
    "If the problem has multiple sub-answers, separate them by commas inside a single \\boxed{}, "
    "e.g. \\boxed{3, 7}.\n\n"
    "Keep your response concise and ensure the boxed answer appears early.\n\n"
    "Example:\n"
    "Question: What is 2 + 3?\n"
    "Reasoning: Adding 2 and 3 gives 5.\n"
    "\\boxed{5}"
)

SYSTEM_PROMPT_MCQ = (
    "You are an expert mathematician. "
    "Read the problem and the answer choices below, then select the single best answer. "
    "Output ONLY the letter of your chosen option inside \\boxed{}, e.g. \\boxed{C}. "
    "Do not include any explanation or additional text.\n\n"
    "Keep your response concise.\n\n"
    "Example:\n"
    "Question: What is 2 + 2?\n"
    "Options:\n"
    "A. 3\n"
    "B. 4\n"
    "C. 5\n"
    "\\boxed{B}"
)


def build_prompt(question: str, options: Optional[list]) -> tuple[str, str]:
    """Return (system_prompt, user_prompt) for a question."""
    if options:
        labels    = [chr(65 + i) for i in range(len(options))]
        opts_text = "\n".join(f"{lbl}. {opt.strip()}" for lbl, opt in zip(labels, options))
        return SYSTEM_PROMPT_MCQ, f"{question}\n\nOptions:\n{opts_text}"
    return SYSTEM_PROMPT_MATH, question


# Verify with samples
for label, item in [("MCQ", mcq_sample), ("Free-form", free_sample)]:
    sys_p, usr_p = build_prompt(item["question"], item.get("options"))
    print(f"── {label} user prompt (first 200 chars) ──")
    print(usr_p[:200], "...\n")

"""## 4.5 Advanced Generation Options

To improve accuracy, experiment with sampling parameters and majority voting.

- **Sampling**: Use deterministic (greedy) for MCQs, stochastic for free-form.
- **Majority Voting**: Generate multiple responses per question and vote on the boxed answer.
"""

# ── Advanced Generation Config ──────────────────────────────────────────────
USE_MAJORITY_VOTING = False  # Set to True to enable voting (slower but potentially more accurate)
NUM_VOTES = 3               # Number of generations per question for voting

# Sampling parameters
SAMPLING_CONFIG = {
    "mcq": {"temperature": 0.0, "top_p": 1.0, "do_sample": False},  # Deterministic for MCQs
    "free_form": {"temperature": 0.3, "top_p": 0.95, "do_sample": True},  # Stochastic for free-form
}

def get_sampling_params_for_question(is_mcq: bool):
    """Return sampling parameters based on question type."""
    config = SAMPLING_CONFIG["mcq" if is_mcq else "free_form"]
    return {**config, "max_new_tokens": MAX_TOKENS}

def extract_boxed_answer(response: str) -> str:
    """Extract the content inside \boxed{}."""
    import re
    match = re.search(r'\\boxed\{([^}]+)\}', response)
    return match.group(1).strip() if match else ""

def majority_vote(responses: list[str]) -> str:
    """Return the most common boxed answer from multiple responses."""
    from collections import Counter
    answers = [extract_boxed_answer(r) for r in responses if extract_boxed_answer(r)]
    if not answers:
        return responses[0] if responses else ""
    return Counter(answers).most_common(1)[0][0]

# Example usage in generation loop (see below)

"""### Experiment with Sampling Parameters

To find the best settings, you can run quick tests on a subset and compare accuracies.
"""

'''# ── Sampling Parameter Experiments ──────────────────────────────────────────
# Run this cell to test different configs on a small subset

def test_sampling_configs():
    # 1. Grab a small subset for quick testing
    test_data = data[:10]

    # 2. Define our parameter configurations
    configs_to_test = [
        {"name": "Greedy", "mcq": {"temperature": 0.0, "do_sample": False}, "free_form": {"temperature": 0.0, "do_sample": False}},
        {"name": "Temp 0.3", "mcq": {"temperature": 0.3, "do_sample": True}, "free_form": {"temperature": 0.3, "do_sample": True}},
        {"name": "Temp 0.5", "mcq": {"temperature": 0.5, "do_sample": True}, "free_form": {"temperature": 0.5, "do_sample": True}},
    ]

    results_summary = {}

    for config in configs_to_test:
        print(f"\nTesting {config['name']}...")

        # Track correct predictions for this specific config run
        correct_count = 0

        # 3. Mini Generation Loop
        for idx, row in enumerate(test_data):
            q_type = row["type"]  # "mcq" or "free_form"

            # Select appropriate generation parameters from the current config
            params = config[q_type]

            # Build the specific prompt structure required for this question type
            prompt = build_mcq_prompt(row) if q_type == "mcq" else build_free_form_prompt(row)

            # Tokenize input and explicitly push tensors to the active GPU
            inputs = tokenizer(prompt, return_tensors="pt").to("cuda")

            generation_kwargs = {
                "max_new_tokens": MAX_NEW_TOKENS,
                "temperature": params["temperature"],
                "do_sample": params["do_sample"],
                "pad_token_id": tokenizer.pad_token_id,
                "eos_token_id": tokenizer.eos_token_id,
                "stopping_criteria": stopping_criteria
            }

            # Only apply top_p configuration if sampling is enabled
            if params["do_sample"]:
                generation_kwargs["top_p"] = 0.9

            # Use torch.inference_mode for maximum speed and lower memory usage
            with torch.inference_mode():
                output_ids = llm.generate(**inputs, **generation_kwargs)

            # Decode the generated tokens into readable string format
            input_length = inputs.input_ids.shape[1]
            generated_text = tokenizer.decode(output_ids[0][input_length:], skip_special_tokens=True)

            # Extract and evaluate the answer inside the \boxed{} tags
            predicted_answer = extract_boxed_answer(generated_text)
            ground_truth = row["answer"]

            # Use the evaluation helper function to handle mathematical or whitespace equivalence
            if evaluate_answer(predicted_answer, ground_truth, q_type):
                correct_count += 1

        # 4. Calculate local accuracy score for this specific config
        accuracy = (correct_count / len(test_data)) * 100
        results_summary[config['name']] = accuracy
        print(f"Finished {config['name']} | Accuracy: {accuracy:.2f}%")

    # 5. Render final comparison overview
    print("\n===============================")
    print("   Accuracy Comparison Result  ")
    print("===============================")
    for name, acc in results_summary.items():
        print(f"{name:<10}: {acc:.2f}%")

# Execute the test suite
test_sampling_configs()'''

"""## 5. Load Model with vLLM (for general case, vLLM is faster)

We load **Qwen3-4B-Thinking-2507** with **INT8 quantization** via BitsAndBytes.  
Setting `load_format="bitsandbytes"` tells vLLM to apply on-the-fly INT8 weight quantization, roughly halving GPU memory usage compared to BF16.

Key parameters:
- `gpu_memory_utilization` — fraction of GPU VRAM reserved for the model and KV cache
- `max_model_len` — maximum sequence length (prompt + generation)
- `max_num_seqs` — maximum number of sequences processed in parallel
"""

import torch
import gc
import os

# Prevent PyTorch from fragmenting the small 15GB T4 memory pool
os.environ["PYTORCH_CUDA_ALLOC_CONF"] = "expandable_segments:True"

# Force flush memory
try:
    del llm, tokenizer
except NameError:
    pass

gc.collect()
torch.cuda.empty_cache()
print("GPU memory cleared and optimized.")

from transformers import AutoModelForCausalLM, AutoTokenizer
import torch

MODEL_ID = "Qwen/Qwen3-4B-Thinking-2507"  # Or your specific notebook's MODEL_ID variable

tokenizer = AutoTokenizer.from_pretrained(MODEL_ID)
tokenizer.pad_token = tokenizer.eos_token

llm = AutoModelForCausalLM.from_pretrained(
    MODEL_ID,
    trust_remote_code=True,
    torch_dtype=torch.float16,  # T4 native precision
    device_map="cuda:0",        # Force strictly to GPU to block CPU offloading
    low_cpu_mem_usage=True,
)

print("Model loaded via pure HF on GPU successfully.")

# ── Early Stopping Criteria ─────────────────────────────────────────────────
from transformers import StoppingCriteria, StoppingCriteriaList

class BoxedStoppingCriteria(StoppingCriteria):
    def __init__(self, tokenizer):
        self.tokenizer = tokenizer
        # Tokenize the start of \boxed{
        self.boxed_start = tokenizer.encode("\\boxed{", add_special_tokens=False)
        self.boxed_start_len = len(self.boxed_start)

    def __call__(self, input_ids, scores, **kwargs):
        # Check if the last tokens match the start of \boxed{
        if input_ids.shape[1] >= self.boxed_start_len:
            last_tokens = input_ids[0, -self.boxed_start_len:].tolist()
            if last_tokens == self.boxed_start:
                return True
        return False

# Create stopping criteria instance
stopping_criteria = StoppingCriteriaList([BoxedStoppingCriteria(tokenizer)])

# Usage: Add stopping_criteria=stopping_criteria to llm.generate() calls

import time
from transformers import TextStreamer
import torch

results = []
start_time = time.time()

# Loop through loaded jsonl data records
for idx, row in enumerate(data):
    batch_start_time = time.time()

    # 1. Check if "options" key exists to determine question type
    is_mcq = bool(row.get("options"))

    # 2. Build the appropriate prompt using your prompt helper
    system_prompt, user_prompt = build_prompt(row["question"], row.get("options"))

    # Format for standard Chat / Instruct templates
    messages = [
        {"role": "system", "content": system_prompt},
        {"role": "user", "content": user_prompt}
    ]
    prompt = tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)

    # Tokenize and push to GPU
    inputs = tokenizer(prompt, return_tensors="pt").to("cuda:0")

    # 3. Dynamic sampling parameters based on question type
    if is_mcq:
        generation_kwargs = {
            "max_new_tokens": 5120,
            "temperature": 0.0,
            "do_sample": False,
            "pad_token_id": tokenizer.pad_token_id,
            "eos_token_id": tokenizer.eos_token_id,
        }
    else:
        generation_kwargs = {
            "max_new_tokens": 5120,
            "temperature": 0.3,
            "top_p": 0.95,
            "do_sample": True,
            "pad_token_id": tokenizer.pad_token_id,
            "eos_token_id": tokenizer.eos_token_id,
        }

    # =====================================================================
    # STREAMER STEP: Stream text live ONLY for the first 3 diagnostic rows
    # =====================================================================
    if idx < 3:
        print(f"\n=================== ITEM {idx+1} LIVE GENERATION ===================")
        print(f"QUESTION:\n{row['question']}\n")
        print("MODEL GENERATION (THINKING + ANSWER):")

        # TextStreamer prints tokens continuously to the console as they come out
        streamer = TextStreamer(tokenizer, skip_prompt=True, skip_special_tokens=True)
        generation_kwargs["streamer"] = streamer

    # Execute Inference via pure HuggingFace Transformers
    with torch.inference_mode():
        output_ids = llm.generate(**inputs, **generation_kwargs)

    input_length = inputs.input_ids.shape[1]
    generated_text = tokenizer.decode(output_ids[0][input_length:], skip_special_tokens=True)

    if idx < 3:
        print("\n==================================================================\n")

    # 4. Extract target answer pattern
    predicted_answer = extract_boxed_answer(generated_text)

    # Append the model prediction structure back into the row data
    row["predicted_answer"] = predicted_answer
    results.append(row)

    if idx % 10 == 0 or idx == len(data) - 1:
        print(f"Processed {idx + 1}/{len(data)} | Batch Time: {time.time() - batch_start_time:.2f}s")

print(f"Inference complete in {time.time() - start_time:.2f} seconds!")

"""## 5. Load Model with Transformers (alternative to vLLM for DataHub)

We load **Qwen3-4B-Thinking-2507** with **INT4 quantization** via BitsAndBytes.  

Key parameters:
- `load_in_4bit` — quantization strategy of INT4
"""

'''import os
import torch
from transformers import AutoTokenizer, AutoModelForCausalLM, BitsAndBytesConfig

# ── Environment Configuration ────────────────────────────────────────────────
os.environ["CUDA_VISIBLE_DEVICES"] = "1"
os.environ["HF_TOKEN"] = "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"

MODEL_ID = "Qwen/Qwen3-4B-Thinking-2507"

# Initialize Tokenizer
tokenizer = AutoTokenizer.from_pretrained(MODEL_ID, trust_remote_code=True)
tokenizer.pad_token = tokenizer.eos_token

# Configure 4-bit Quantization to optimize Kaggle VRAM
bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_compute_dtype=torch.bfloat16,
    bnb_4bit_use_double_quant=True,
    bnb_4bit_quant_type="nf4"
)

# Load Model
try:
    print(f"Loading {MODEL_ID} in 4-bit...")
    # Force pure bfloat16 execution onto the GPU directly without CPU fallback
    llm = AutoModelForCausalLM.from_pretrained(
        MODEL_ID,
        trust_remote_code=True,
        torch_dtype=torch.bfloat16,
        device_map="cuda:0", # Force it to GPU 0 instead of "auto" which triggers CPU split
        low_cpu_mem_usage=True,
    )
except Exception as exc:
    print("4-bit load failed, retrying in pure bfloat16:", exc)
    llm = AutoModelForCausalLM.from_pretrained(
        MODEL_ID,
        trust_remote_code=True,
        torch_dtype=torch.bfloat16,
        device_map="auto",
        low_cpu_mem_usage=True,
    )'''

"""## 6. Generate Responses

We format every question into a chat-template prompt, then call `llm.generate()` in one batched pass.  
vLLM handles batching and scheduling internally — no manual batching needed.

### Generate with vLLM
"""

# # Build prompts for first 5 entries
# prompts = []
# for item in data[:5]:
#     system, user = build_prompt(item["question"], item.get("options"))
#     prompt_text = tokenizer.apply_chat_template(
#         [{"role": "system", "content": system},
#          {"role": "user",   "content": user}],
#         tokenize=False,
#         add_generation_prompt=True,
#     )
#     prompts.append(prompt_text)

# # Generate
# print(f"Generating responses for {len(prompts)} questions...")
# outputs = llm.generate(prompts, sampling_params=sampling_params)

# responses = [out.outputs[0].text.strip() for out in outputs]

# # Preview first 3
# for i in range(min(3, len(responses))):
#     print(f"\n── Response {i} (id={data[i].get('id')}) ──")
#     print(responses[i][:400], "..." if len(responses[i]) > 400 else "")

"""### Generate with Transformers (for Datahub)"""

'''import time
import torch
torch.cuda.empty_cache()
from torch.utils.data import DataLoader
from tqdm import tqdm

# ── Generation Configuration ────────────────────────────────────────────────
MAX_NEW_TOKENS = 256  # Reduced to avoid CUDA OOM on 14GB GPUs
BATCH_SIZE = 1  # Use a small batch size to keep VRAM usage low

generation_kwargs = {
    "max_new_tokens": MAX_NEW_TOKENS,
    "temperature": 0.7 if USE_MAJORITY_VOTING else 0.0,
    "top_p": 0.9,
    "do_sample": True if USE_MAJORITY_VOTING else False,
    "pad_token_id": tokenizer.pad_token_id,
    "eos_token_id": tokenizer.eos_token_id,
}

tokenizer.padding_side = "left"

# ── Build Prompts ────────────────────────────────────────────────────────────
N_TO_PROCESS = max(len(data), 10)  # Start with a small subset for testing
prompts = []

for item in data[:N_TO_PROCESS]:
    system, user = build_prompt(item["question"], item.get("options"))
    prompt_text = tokenizer.apply_chat_template(
        [{"role": "system", "content": system},
         {"role": "user",   "content": user}],
        tokenize=False,
        add_generation_prompt=True,
    )
    prompts.append(prompt_text)

# ── High-Performance Batch Processing Loop ───────────────────────────────────
print(f"Generating responses for {len(prompts)} questions using HF Batching (Batch Size = {BATCH_SIZE})...")
responses = [[] for _ in range(len(prompts))] if USE_MAJORITY_VOTING else []

NUM_RUNS = NUM_VOTES if USE_MAJORITY_VOTING else 1
PRINT_EVERY_N_BATCHES = 10  # Change this to 1 if you want to see every single batch

start_time = time.time()

for run in range(NUM_RUNS):
    if USE_MAJORITY_VOTING:
        print(f"\n" + "="*40 + f"\n--- Starting Voting Round {run + 1}/{NUM_VOTES} ---\n" + "="*40)

    data_loader = DataLoader(prompts, batch_size=BATCH_SIZE, shuffle=False)

    current_idx = 0
    for batch_num, batch in enumerate(tqdm(data_loader, desc="Processing Batches"), start=1):
        batch_start_time = time.time()

        # Tokenize batch with truncation to keep the prompt length manageable
        inputs = tokenizer(batch, return_tensors="pt", padding=True, truncation=True, max_length=2048).to(llm.device)
        input_lens = [inputs["attention_mask"][j].sum().item() for j in range(len(batch))]

        with torch.no_grad():
            output_ids = llm.generate(**inputs, **generation_kwargs)

        batch_elapsed = time.time() - batch_start_time

        # Track if we should print a preview for this batch
        should_print_preview = (batch_num == 1 or batch_num % PRINT_EVERY_N_BATCHES == 0)

        if should_print_preview:
            print(f"\n\n[Batch {batch_num}] Generated in {batch_elapsed:.2f}s | Sample text output from first item:")
            print("-" * 50)

        # Extract generations cleanly per item in the batch
        for j, output_id in enumerate(output_ids):
            new_tokens = output_id[input_lens[j]:]
            generated_text = tokenizer.decode(new_tokens, skip_special_tokens=True).strip()

            # Print a snippet of the first item in the batch if requested
            if should_print_preview and j == 0:
                # Preview just the first 350 characters to keep stdout readable
                preview_snippet = generated_text[:350] + "..." if len(generated_text) > 350 else generated_text
                print(preview_snippet)
                print("-" * 50 + "\n")

            if USE_MAJORITY_VOTING:
                responses[current_idx + j].append(generated_text)
            else:
                responses.append(generated_text)

        current_idx += BATCH_SIZE

# ── Resolve Majority Voting Consensus if Applicable ──────────────────────────
if USE_MAJORITY_VOTING:
    print("\nComputing consensus choices from gathered votes...")
    final_responses = []
    for candidate_list in responses:
        final_responses.append(majority_vote(candidate_list))
    responses = final_responses

total_duration = time.time() - start_time
print(f"\nGeneration Complete! Finished in {total_duration/60:.2f} minutes.")'''

"""## 7. Score Responses

Scoring differs by question type:

- **MCQ**: extract the predicted letter from `\boxed{}` and compare to the gold letter (exact match).
- **Free-form**: use `Judger.auto_judge()` which handles symbolic and numeric equivalence.

Each result record contains `{id, is_mcq, gold, response, correct}`.
"""

print(type(results))

def normalize_answer(text: str) -> str:
    text = str(text).strip()
    text = re.sub(r"\s+", " ", text)
    return text

# Load Judger for free-form scoring if available
has_judger = False
try:
    if (ROOT / "judger.py").exists() or (ROOT / "stage1").exists():
        sys.path.insert(0, str(ROOT))
    from judger import Judger
    judger = Judger(strict_extract=False)
    has_judger = True
except Exception as exc:
    print("Judger not available; falling back to string-based free-form scoring.", exc)

# Loop directly through your existing results list in memory
for item in tqdm(results, desc="Scoring"):
    is_mcq = bool(item.get("options"))
    gold = item["answer"]

    # Fallback safety: Use 'predicted_answer' since 'response' wasn't explicitly saved
    if "response" not in item:
        item["response"] = item.get("predicted_answer", "")

    response = item["response"]

    if is_mcq:
        correct = score_mcq(response, str(gold))
    else:
        if has_judger:
            gold_list = gold if isinstance(gold, list) else [gold]
            try:
                correct = judger.auto_judge(
                    pred=response,
                    gold=gold_list,
                    options=[[]] * len(gold_list),
                )
            except Exception:
                correct = False
        else:
            correct = normalize_answer(response) == normalize_answer(gold)

    # Save validation correctness flag
    item["correct"] = correct

print(f"Scoring complete. {len(results)} results.")

"""## 8. Summary

Print accuracy broken down by question type.
"""

mcq_res  = [r for r in results if r["is_mcq"]]
free_res = [r for r in results if not r["is_mcq"]]

def acc(subset):
    return sum(r["correct"] for r in subset) / len(subset) * 100 if subset else 0.0

print("=" * 50)
print("EVALUATION RESULTS")
print("=" * 50)
print(f"  MCQ        : {sum(r['correct'] for r in mcq_res):4d} / {len(mcq_res):4d}  ({acc(mcq_res):.2f}%)")
print(f"  Free-form  : {sum(r['correct'] for r in free_res):4d} / {len(free_res):4d}  ({acc(free_res):.2f}%)")
print(f"  Overall    : {sum(r['correct'] for r in results):4d} / {len(results):4d}  ({acc(results):.2f}%)")
print("=" * 50)

"""## 9. Save Results

Results are written as newline-delimited JSON.

**With evaluation** (public set — you have ground-truth):  
Each line: `{id, is_mcq, gold, response, correct}`

**Without evaluation** (private test set — no ground-truth available):  
Each line: `{id, is_mcq, response}` — omit `gold` and `correct`.

Toggle `SAVE_EVAL` below accordingly.
"""

SAVE_EVAL = False   # Set to False when running on the private test set

out_path = Path(OUTPUT_PATH)
out_path.parent.mkdir(parents=True, exist_ok=True)

with open(out_path, "w") as f:
    for r in results:
        if SAVE_EVAL:
            record = {"id": r["id"], "is_mcq": r["is_mcq"], "gold": r["gold"],
                      "response": r["response"], "correct": r["correct"]}
        else:
            record = {"id": r["id"], "is_mcq": r["is_mcq"], "response": r["response"]}
        f.write(json.dumps(record) + "\n")

print(f"Saved {len(results)} records to {out_path}")

"""## Next Steps

This notebook gives you a working baseline. Here are directions to improve your score:

- **Prompt engineering** — add a concise worked example or stronger instructions in `build_prompt()`.
  - For MCQs, explicitly ask for only the final answer letter inside `\boxed{}`.
  - For free-form math, ask for step-by-step reasoning plus a final boxed result.
- **Sampling parameters** — compare deterministic and stochastic decoding.
  - Use `temperature=0.0` for stable MCQ predictions and `0.3-0.5` for free-form reasoning.
  - Try `top_p=0.95` or `top_k=20` and see which gives the best balance of accuracy.
- **Majority voting** — generate multiple outputs per question and choose the most frequent boxed answer.
  - This can boost robustness, especially on ambiguous problems.
- **Evaluation** — keep `SAVE_EVAL=True` on public data, then switch to `False` only for private test predictions.
- **Fine-tuning** — once prompt and sampling are tuned, use the competition’s fine-tuning path if allowed.

Good luck!

## Results Presentation

Load and analyze the results from the starter code and preliminary implementations.
"""

# ── Load Results ─────────────────────────────────────────────────────────────
import json
from pathlib import Path
from collections import Counter
import matplotlib.pyplot as plt
import pandas as pd

# Load results from the output file
results_path = Path(OUTPUT_PATH)
if results_path.exists():
    results = [json.loads(line) for line in open(results_path)]
    print(f"Loaded {len(results)} results from {results_path}")
else:
    print(f"Results file {results_path} not found. Run the generation and scoring cells first.")
    results = []

# Separate MCQ and free-form results
mcq_results = [r for r in results if r["is_mcq"]]
free_results = [r for r in results if not r["is_mcq"]]

# Compute accuracies
def compute_accuracy(res_list):
    if not res_list:
        return 0.0
    return sum(r["correct"] for r in res_list) / len(res_list) * 100

overall_acc = compute_accuracy(results)
mcq_acc = compute_accuracy(mcq_results)
free_acc = compute_accuracy(free_results)

print(f"Overall Accuracy: {overall_acc:.2f}%")
print(f"MCQ Accuracy: {mcq_acc:.2f}% ({len(mcq_results)} questions)")
print(f"Free-form Accuracy: {free_acc:.2f}% ({len(free_results)} questions)")

"""# ── Quantitative Results Table ──────────────────────────────────────────────
metrics_df = pd.DataFrame({
    "Metric": ["Total Questions", "MCQ Questions", "Free-form Questions", "Overall Accuracy", "MCQ Accuracy", "Free-form Accuracy"],
    "Value": [len(results), len(mcq_results), len(free_results), f"{overall_acc:.2f}%", f"{mcq_acc:.2f}%", f"{free_acc:.2f}%"]
})
display(metrics_df)

### Qualitative Results: Accuracy by Question Type
"""

# ── Accuracy Visualization ───────────────────────────────────────────────────
fig, ax = plt.subplots(figsize=(8, 5))
categories = ['Overall', 'MCQ', 'Free-form']
accuracies = [overall_acc, mcq_acc, free_acc]
bars = ax.bar(categories, accuracies, color=['blue', 'green', 'orange'])
ax.set_ylabel('Accuracy (%)')
ax.set_title('Model Accuracy by Question Type')
ax.set_ylim(0, 100)

# Add value labels on bars
for bar, acc in zip(bars, accuracies):
    height = bar.get_height()
    ax.text(bar.get_x() + bar.get_width()/2., height + 1,
            f'{acc:.1f}%', ha='center', va='bottom')

plt.show()

"""# ── Example Responses ──────────────────────────────────────────────────────
print("### Correct MCQ Example:")
correct_mcq = next((r for r in mcq_results if r["correct"]), None)
if correct_mcq:
    print(f"Response: {correct_mcq['response'][:300]}...")
    print(f"Gold: {correct_mcq['gold']}")
else:
    print("No correct MCQ found.")

print("\n### Incorrect Free-form Example:")
incorrect_free = next((r for r in free_results if not r["correct"]), None)
if incorrect_free:
    print(f"Response: {incorrect_free['response'][:300]}...")
    print(f"Gold: {incorrect_free['gold']}")
else:
    print("No incorrect free-form found.")

print("\n### Negative Finding:")
print("The model often produces verbose reasoning for simple problems and misses π in infinite integrals.")

## Summary

The starter code achieves baseline performance with room for improvement through prompt engineering, sampling adjustments, and majority voting. Key insights include higher accuracy on MCQs vs. free-form, and common failure modes in complex math problems.

### Fine-Tuning Preparation

Once prompts and sampling are optimized, prepare for fine-tuning:

1. **Collect training data**: Use the public dataset or similar math problems.
2. **Format as conversations**: Convert to chat format with system/user/assistant roles.
3. **Choose method**:
   - **LoRA**: Efficient fine-tuning with low-rank adapters (use PEFT library).
   - **GRPO**: Reward-based optimization for math reasoning (requires RL setup).
4. **Training script**: Implement with transformers or vLLM.
5. **Evaluation**: Test on held-out public data before submitting.

Example LoRA setup (pseudocode):
```python
from peft import LoraConfig, get_peft_model
from transformers import TrainingArguments, Trainer

# Load base model
model = AutoModelForCausalLM.from_pretrained(MODEL_ID, ...)

# LoRA config
lora_config = LoraConfig(
    r=16, lora_alpha=32, target_modules=["q_proj", "v_proj"],
    lora_dropout=0.05, bias="none", task_type="CAUSAL_LM"
)
model = get_peft_model(model, lora_config)

# Train...
```

See course resources for full implementation.

## 10. GRPO Fine-Tuning

This section implements a simple reward-guided policy optimization loop. It uses LoRA for parameter-efficient adaptation, samples candidate responses, scores them with the existing judging logic, and updates the model via policy gradients.
"""

# ── GRPO Fine-Tuning Implementation ────────────────────────────────────────
# NOTE: This is set up for quick testing on 5 samples. Adjust GRPO_TRAIN_SIZE for more data.
# Fixed memory issue by generating without gradients first, then computing logprobs.
import torch
from torch.optim import AdamW
from transformers import AutoModelForCausalLM, AutoTokenizer, BitsAndBytesConfig
from peft import LoraConfig, get_peft_model

# Optional: use LoRA adapters to keep fine-tuning lightweight
USE_LORA = True
LORA_R = 16
LORA_ALPHA = 32
LORA_DROPOUT = 0.05

# Use a smaller subset for initial GRPO experiments
GRPO_TRAIN_SIZE = 5  # Changed to 5 for quick testing
GRPO_EPOCHS = 1      # Reduced to 1 epoch for faster testing
GRPO_MAX_NEW_TOKENS = 16  # Reduced further for lower memory footprint
GRPO_TEMPERATURE = 1.0
GRPO_TOP_P = 0.95
BASELINE_REWARD = 0.5
LEARNING_RATE = 2e-5

DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# Load model and tokenizer for GRPO
print(f"Loading model for GRPO on {DEVICE}...")

tokenizer = AutoTokenizer.from_pretrained(MODEL_ID, trust_remote_code=True)
tokenizer.pad_token = tokenizer.eos_token

bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_compute_dtype=torch.float16,
    bnb_4bit_use_double_quant=True,
)

model = AutoModelForCausalLM.from_pretrained(
    MODEL_ID,
    trust_remote_code=True,
    quantization_config=bnb_config,
    device_map="auto",
)
model.config.pad_token_id = tokenizer.eos_token_id

if USE_LORA:
    lora_config = LoraConfig(
        r=LORA_R,
        lora_alpha=LORA_ALPHA,
        target_modules=["q_proj", "v_proj"],
        lora_dropout=LORA_DROPOUT,
        bias="none",
        task_type="CAUSAL_LM",
    )
    model = get_peft_model(model, lora_config)

model.train()

# Reward function using the existing scoring logic

def extract_letter(text: str) -> str:
    m = re.search(r"\\boxed\{([A-Za-z])\}", text)
    if m:
        return m.group(1).upper()
    matches = re.findall(r"\b([A-Z])\b", text.upper())
    return matches[-1] if matches else ""


def score_mcq(response: str, gold_letter: str) -> bool:
    return extract_letter(response) == gold_letter.strip().upper()


def compute_reward(item, response: str) -> float:
    if item.get("options"):
        return 1.0 if score_mcq(response, str(item["answer"])) else 0.0

    gold_list = item["answer"] if isinstance(item["answer"], list) else [item["answer"]]
    try:
        correct = judger.auto_judge(pred=response, gold=gold_list, options=[[]] * len(gold_list))
        return 1.0 if correct else 0.0
    except Exception:
        return 0.0


def build_grpo_prompt(item):
    system, user = build_prompt(item["question"], item.get("options"))
    return tokenizer.apply_chat_template(
        [{"role": "system", "content": system}, {"role": "user", "content": user}],
        tokenize=False,
        add_generation_prompt=True,
    )


def sample_response_and_logprob(prompt_text: str):
    input_ids = tokenizer(prompt_text, return_tensors="pt", add_special_tokens=False).input_ids
    model_device = next(model.parameters()).device
    input_ids = input_ids.to(model_device)

    # Generate the full sequence without gradients to save memory
    with torch.no_grad():
        generated = model.generate(
            input_ids,
            max_new_tokens=GRPO_MAX_NEW_TOKENS,
            temperature=GRPO_TEMPERATURE,
            top_p=GRPO_TOP_P,
            do_sample=True,
            pad_token_id=tokenizer.eos_token_id,
        )

    generated_tokens = generated[:, input_ids.shape[1]:]
    response = tokenizer.decode(generated_tokens[0], skip_special_tokens=True).strip()

    # Now compute logprobs with gradients for the generated tokens using incremental decoding
    with torch.enable_grad():
        outputs = model(input_ids, use_cache=True)
        past_key_values = outputs.past_key_values
        total_logprob = 0.0

        for t in range(generated_tokens.size(1)):
            logits = outputs.logits[:, -1, :]
            logprobs = torch.log_softmax(logits / GRPO_TEMPERATURE, dim=-1)
            token = generated_tokens[:, t].unsqueeze(-1)
            token_logprob = logprobs.gather(-1, token).squeeze(-1)
            total_logprob = total_logprob + token_logprob

            outputs = model(token, past_key_values=past_key_values, use_cache=True)
            past_key_values = outputs.past_key_values

        total_logprob = total_logprob.sum()

    return response, total_logprob


# Create a small GRPO training set from the public data
train_items = data[:GRPO_TRAIN_SIZE]
optimizer = AdamW(model.parameters(), lr=LEARNING_RATE)

for epoch in range(1, GRPO_EPOCHS + 1):
    epoch_loss = 0.0
    for item in train_items:
        prompt_text = build_grpo_prompt(item)
        response, logprob_sum = sample_response_and_logprob(prompt_text)
        reward = compute_reward(item, response)
        advantage = reward - BASELINE_REWARD
        loss = -(advantage) * logprob_sum

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        epoch_loss += loss.item()


    avg_loss = epoch_loss / len(train_items)
    print(f"Saved GRPO model to {output_dir}")

    print(f"Epoch {epoch}/{GRPO_EPOCHS} - avg loss: {avg_loss:.4f}")
    model.save_pretrained(output_dir)

output_dir.mkdir(parents=True, exist_ok=True)

# Save the GRPO-adapted modeloutput_dir = Path("grpo_finetuned_model")

import json
import os
import re
import sys
from pathlib import Path
from typing import Optional
ROOT = Path('/kaggle/input/datasets/magnuschiu/important/aaaa')

# ── Configuration ─────────────────────────────────────────────────────────────
MODEL_ID    = "Qwen/Qwen3-4B-Thinking-2507"
GPU_ID      = "1"                    # CUDA_VISIBLE_DEVICES
DATA_PATH   = ROOT / "stage1" / "private.jsonl"
if not DATA_PATH.exists():
    DATA_PATH = ROOT / "private.jsonl"
if not DATA_PATH.exists():
    candidate_files = list(ROOT.glob("**/public.jsonl")) + list(ROOT.glob("**/private.jsonl"))
    DATA_PATH = candidate_files[0] if candidate_files else ROOT / "math portion" / "public.jsonl"
OUTPUT_PATH = ROOT / "results" / "starter_results.jsonl"
MAX_TOKENS  = 9182                 # lower max tokens for faster responses; increase only if needed

os.environ["CUDA_VISIBLE_DEVICES"] = GPU_ID

from transformers import AutoTokenizer
from vllm import LLM, SamplingParams
from tqdm import tqdm

import json
import pandas as pd

# ── Corrected Line-by-Line JSONL Data Loader ─────────────────────────────────
def load_data(file_path):
    parsed_data = []
    with open(file_path, 'r', encoding='utf-8') as file:
        for line_num, line in enumerate(file, 1):
            clean_line = line.strip()
            if not clean_line:
                continue  # Skip empty lines cleanly
            try:
                parsed_data.append(json.loads(clean_line))
            except json.JSONDecodeError as e:
                print(f"Skipping malformed JSON on line {line_num}: {e}")
    return parsed_data

# ── Execute Loading ──────────────────────────────────────────────────────────
data = load_data(str(DATA_PATH))

n_mcq = sum(bool(d.get("options")) for d in data)
n_free = sum(not d.get("options") for d in data)
print(f"Loaded {len(data)} questions  ({n_mcq} MCQ, {n_free} free-form)")
print(f"Using dataset: {DATA_PATH}")

# Preview one MCQ and one free-form item
mcq_sample = next((d for d in data if d.get("options")), None)
free_sample = next((d for d in data if not d.get("options")), None)

if mcq_sample:
    print("\n── MCQ sample ──")
    print(json.dumps(mcq_sample, indent=2))
else:
    print("\n── No MCQ sample found in dataset ──")

if free_sample:
    print("\n── Free-form sample ──")
    print(json.dumps(free_sample, indent=2))
else:
    print("\n── No Free-form sample found in dataset ──")

from transformers import AutoModelForCausalLM, AutoTokenizer
import torch

MODEL_ID = "Qwen/Qwen3-4B-Thinking-2507"  # Or your specific notebook's MODEL_ID variable

tokenizer = AutoTokenizer.from_pretrained(MODEL_ID)
tokenizer.pad_token = tokenizer.eos_token

llm = AutoModelForCausalLM.from_pretrained(
    MODEL_ID,
    trust_remote_code=True,
    torch_dtype=torch.float16,  # T4 native precision
    device_map="cuda:0",        # Force strictly to GPU to block CPU offloading
    low_cpu_mem_usage=True,
)

print("Model loaded via pure HF on GPU successfully.")

# ── Early Stopping Criteria ─────────────────────────────────────────────────
from transformers import StoppingCriteria, StoppingCriteriaList

class BoxedStoppingCriteria(StoppingCriteria):
    def __init__(self, tokenizer):
        self.tokenizer = tokenizer
        # Tokenize the start of \boxed{
        self.boxed_start = tokenizer.encode("\\boxed{", add_special_tokens=False)
        self.boxed_start_len = len(self.boxed_start)

    def __call__(self, input_ids, scores, **kwargs):
        # Check if the last tokens match the start of \boxed{
        if input_ids.shape[1] >= self.boxed_start_len:
            last_tokens = input_ids[0, -self.boxed_start_len:].tolist()
            if last_tokens == self.boxed_start:
                return True
        return False

# Create stopping criteria instance
stopping_criteria = StoppingCriteriaList([BoxedStoppingCriteria(tokenizer)])

# Usage: Add stopping_criteria=stopping_criteria to llm.generate() calls

import time
from transformers import TextStreamer
import torch

results = []
start_time = time.time()

# Loop through loaded jsonl data records
for idx, row in enumerate(data):
    batch_start_time = time.time()

    # 1. Check if "options" key exists to determine question type
    is_mcq = bool(row.get("options"))

    # 2. Build the appropriate prompt using your prompt helper
    system_prompt, user_prompt = build_prompt(row["question"], row.get("options"))

    # Format for standard Chat / Instruct templates
    messages = [
        {"role": "system", "content": system_prompt},
        {"role": "user", "content": user_prompt}
    ]
    prompt = tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)

    # Tokenize and push to GPU
    inputs = tokenizer(prompt, return_tensors="pt").to("cuda:0")

    # 3. Dynamic sampling parameters based on question type
    if is_mcq:
        generation_kwargs = {
            "max_new_tokens": 5120,
            "temperature": 0.0,
            "do_sample": False,
            "pad_token_id": tokenizer.pad_token_id,
            "eos_token_id": tokenizer.eos_token_id,
        }
    else:
        generation_kwargs = {
            "max_new_tokens": 5120,
            "temperature": 0.3,
            "top_p": 0.95,
            "do_sample": True,
            "pad_token_id": tokenizer.pad_token_id,
            "eos_token_id": tokenizer.eos_token_id,
        }

    # =====================================================================
    # STREAMER STEP: Stream text live ONLY for the first 3 diagnostic rows
    # =====================================================================
    if idx < 3:
        print(f"\n=================== ITEM {idx+1} LIVE GENERATION ===================")
        print(f"QUESTION:\n{row['question']}\n")
        print("MODEL GENERATION (THINKING + ANSWER):")

        # TextStreamer prints tokens continuously to the console as they come out
        streamer = TextStreamer(tokenizer, skip_prompt=True, skip_special_tokens=True)
        generation_kwargs["streamer"] = streamer

    # Execute Inference via pure HuggingFace Transformers
    with torch.inference_mode():
        output_ids = llm.generate(**inputs, **generation_kwargs)

    input_length = inputs.input_ids.shape[1]
    generated_text = tokenizer.decode(output_ids[0][input_length:], skip_special_tokens=True)

    if idx < 3:
        print("\n==================================================================\n")

    # 4. Extract target answer pattern
    predicted_answer = extract_boxed_answer(generated_text)

    # Append the model prediction structure back into the row data
    row["predicted_answer"] = predicted_answer
    results.append(row)

    if idx % 10 == 0 or idx == len(data) - 1:
        print(f"Processed {idx + 1}/{len(data)} | Batch Time: {time.time() - batch_start_time:.2f}s")

print(f"Inference complete in {time.time() - start_time:.2f} seconds!")